//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannelAdvisorAccess.ListingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.channeladvisor.com/webservices/", ConfigurationName="ListingService.ListingServiceSoap")]
    public interface ListingServiceSoap {
        
        // CODEGEN: Generating message contract since message WithdrawListingsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://api.channeladvisor.com/webservices/WithdrawListings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ChannelAdvisorAccess.ListingService.WithdrawListingsResponse WithdrawListings(ChannelAdvisorAccess.ListingService.WithdrawListingsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://api.channeladvisor.com/webservices/WithdrawListings", ReplyAction="*")]
        System.IAsyncResult BeginWithdrawListings(ChannelAdvisorAccess.ListingService.WithdrawListingsRequest request, System.AsyncCallback callback, object asyncState);
        
        ChannelAdvisorAccess.ListingService.WithdrawListingsResponse EndWithdrawListings(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since message PingRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://api.channeladvisor.com/webservices/Ping", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ChannelAdvisorAccess.ListingService.PingResponse Ping(ChannelAdvisorAccess.ListingService.PingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://api.channeladvisor.com/webservices/Ping", ReplyAction="*")]
        System.IAsyncResult BeginPing(ChannelAdvisorAccess.ListingService.PingRequest request, System.AsyncCallback callback, object asyncState);
        
        ChannelAdvisorAccess.ListingService.PingResponse EndPing(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class APICredentials : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string developerKeyField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DeveloperKey {
            get {
                return this.developerKeyField;
            }
            set {
                this.developerKeyField = value;
                this.RaisePropertyChanged("DeveloperKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class APIResultOfString : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultStatus statusField;
        
        private int messageCodeField;
        
        private string messageField;
        
        private string dataField;
        
        private string resultDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResultStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int MessageCode {
            get {
                return this.messageCodeField;
            }
            set {
                this.messageCodeField = value;
                this.RaisePropertyChanged("MessageCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ResultData {
            get {
                return this.resultDataField;
            }
            set {
                this.resultDataField = value;
                this.RaisePropertyChanged("ResultData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public enum ResultStatus {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Failure,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class APIResultOfInt32 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultStatus statusField;
        
        private int messageCodeField;
        
        private string messageField;
        
        private string dataField;
        
        private int resultDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResultStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int MessageCode {
            get {
                return this.messageCodeField;
            }
            set {
                this.messageCodeField = value;
                this.RaisePropertyChanged("MessageCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int ResultData {
            get {
                return this.resultDataField;
            }
            set {
                this.resultDataField = value;
                this.RaisePropertyChanged("ResultData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WithdrawListings", WrapperNamespace="http://api.channeladvisor.com/webservices/", IsWrapped=true)]
    public partial class WithdrawListingsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
        public ChannelAdvisorAccess.ListingService.APICredentials APICredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string accountID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=1)]
        public string[] skuList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=2)]
        public string[] listingIDList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=3)]
        public string withdrawReason;
        
        public WithdrawListingsRequest() {
        }
        
        public WithdrawListingsRequest(ChannelAdvisorAccess.ListingService.APICredentials APICredentials, string accountID, string[] skuList, string[] listingIDList, string withdrawReason) {
            this.APICredentials = APICredentials;
            this.accountID = accountID;
            this.skuList = skuList;
            this.listingIDList = listingIDList;
            this.withdrawReason = withdrawReason;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WithdrawListingsResponse", WrapperNamespace="http://api.channeladvisor.com/webservices/", IsWrapped=true)]
    public partial class WithdrawListingsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=0)]
        public ChannelAdvisorAccess.ListingService.APIResultOfInt32 WithdrawListingsResult;
        
        public WithdrawListingsResponse() {
        }
        
        public WithdrawListingsResponse(ChannelAdvisorAccess.ListingService.APIResultOfInt32 WithdrawListingsResult) {
            this.WithdrawListingsResult = WithdrawListingsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Ping", WrapperNamespace="http://api.channeladvisor.com/webservices/", IsWrapped=true)]
    public partial class PingRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
        public ChannelAdvisorAccess.ListingService.APICredentials APICredentials;
        
        public PingRequest() {
        }
        
        public PingRequest(ChannelAdvisorAccess.ListingService.APICredentials APICredentials) {
            this.APICredentials = APICredentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PingResponse", WrapperNamespace="http://api.channeladvisor.com/webservices/", IsWrapped=true)]
    public partial class PingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=0)]
        public ChannelAdvisorAccess.ListingService.APIResultOfString PingResult;
        
        public PingResponse() {
        }
        
        public PingResponse(ChannelAdvisorAccess.ListingService.APIResultOfString PingResult) {
            this.PingResult = PingResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ListingServiceSoapChannel : ChannelAdvisorAccess.ListingService.ListingServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WithdrawListingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public WithdrawListingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ChannelAdvisorAccess.ListingService.APIResultOfInt32 Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ChannelAdvisorAccess.ListingService.APIResultOfInt32)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public PingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ChannelAdvisorAccess.ListingService.APIResultOfString Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ChannelAdvisorAccess.ListingService.APIResultOfString)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListingServiceSoapClient : System.ServiceModel.ClientBase<ChannelAdvisorAccess.ListingService.ListingServiceSoap>, ChannelAdvisorAccess.ListingService.ListingServiceSoap {
        
        private BeginOperationDelegate onBeginWithdrawListingsDelegate;
        
        private EndOperationDelegate onEndWithdrawListingsDelegate;
        
        private System.Threading.SendOrPostCallback onWithdrawListingsCompletedDelegate;
        
        private BeginOperationDelegate onBeginPingDelegate;
        
        private EndOperationDelegate onEndPingDelegate;
        
        private System.Threading.SendOrPostCallback onPingCompletedDelegate;
        
        public ListingServiceSoapClient() {
        }
        
        public ListingServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ListingServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListingServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListingServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<WithdrawListingsCompletedEventArgs> WithdrawListingsCompleted;
        
        public event System.EventHandler<PingCompletedEventArgs> PingCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChannelAdvisorAccess.ListingService.WithdrawListingsResponse ChannelAdvisorAccess.ListingService.ListingServiceSoap.WithdrawListings(ChannelAdvisorAccess.ListingService.WithdrawListingsRequest request) {
            return base.Channel.WithdrawListings(request);
        }
        
        public ChannelAdvisorAccess.ListingService.APIResultOfInt32 WithdrawListings(ChannelAdvisorAccess.ListingService.APICredentials APICredentials, string accountID, string[] skuList, string[] listingIDList, string withdrawReason) {
            ChannelAdvisorAccess.ListingService.WithdrawListingsRequest inValue = new ChannelAdvisorAccess.ListingService.WithdrawListingsRequest();
            inValue.APICredentials = APICredentials;
            inValue.accountID = accountID;
            inValue.skuList = skuList;
            inValue.listingIDList = listingIDList;
            inValue.withdrawReason = withdrawReason;
            ChannelAdvisorAccess.ListingService.WithdrawListingsResponse retVal = ((ChannelAdvisorAccess.ListingService.ListingServiceSoap)(this)).WithdrawListings(inValue);
            return retVal.WithdrawListingsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ChannelAdvisorAccess.ListingService.ListingServiceSoap.BeginWithdrawListings(ChannelAdvisorAccess.ListingService.WithdrawListingsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginWithdrawListings(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginWithdrawListings(ChannelAdvisorAccess.ListingService.APICredentials APICredentials, string accountID, string[] skuList, string[] listingIDList, string withdrawReason, System.AsyncCallback callback, object asyncState) {
            ChannelAdvisorAccess.ListingService.WithdrawListingsRequest inValue = new ChannelAdvisorAccess.ListingService.WithdrawListingsRequest();
            inValue.APICredentials = APICredentials;
            inValue.accountID = accountID;
            inValue.skuList = skuList;
            inValue.listingIDList = listingIDList;
            inValue.withdrawReason = withdrawReason;
            return ((ChannelAdvisorAccess.ListingService.ListingServiceSoap)(this)).BeginWithdrawListings(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChannelAdvisorAccess.ListingService.WithdrawListingsResponse ChannelAdvisorAccess.ListingService.ListingServiceSoap.EndWithdrawListings(System.IAsyncResult result) {
            return base.Channel.EndWithdrawListings(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ChannelAdvisorAccess.ListingService.APIResultOfInt32 EndWithdrawListings(System.IAsyncResult result) {
            ChannelAdvisorAccess.ListingService.WithdrawListingsResponse retVal = ((ChannelAdvisorAccess.ListingService.ListingServiceSoap)(this)).EndWithdrawListings(result);
            return retVal.WithdrawListingsResult;
        }
        
        private System.IAsyncResult OnBeginWithdrawListings(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ChannelAdvisorAccess.ListingService.APICredentials APICredentials = ((ChannelAdvisorAccess.ListingService.APICredentials)(inValues[0]));
            string accountID = ((string)(inValues[1]));
            string[] skuList = ((string[])(inValues[2]));
            string[] listingIDList = ((string[])(inValues[3]));
            string withdrawReason = ((string)(inValues[4]));
            return this.BeginWithdrawListings(APICredentials, accountID, skuList, listingIDList, withdrawReason, callback, asyncState);
        }
        
        private object[] OnEndWithdrawListings(System.IAsyncResult result) {
            ChannelAdvisorAccess.ListingService.APIResultOfInt32 retVal = this.EndWithdrawListings(result);
            return new object[] {
                    retVal};
        }
        
        private void OnWithdrawListingsCompleted(object state) {
            if ((this.WithdrawListingsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.WithdrawListingsCompleted(this, new WithdrawListingsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void WithdrawListingsAsync(ChannelAdvisorAccess.ListingService.APICredentials APICredentials, string accountID, string[] skuList, string[] listingIDList, string withdrawReason) {
            this.WithdrawListingsAsync(APICredentials, accountID, skuList, listingIDList, withdrawReason, null);
        }
        
        public void WithdrawListingsAsync(ChannelAdvisorAccess.ListingService.APICredentials APICredentials, string accountID, string[] skuList, string[] listingIDList, string withdrawReason, object userState) {
            if ((this.onBeginWithdrawListingsDelegate == null)) {
                this.onBeginWithdrawListingsDelegate = new BeginOperationDelegate(this.OnBeginWithdrawListings);
            }
            if ((this.onEndWithdrawListingsDelegate == null)) {
                this.onEndWithdrawListingsDelegate = new EndOperationDelegate(this.OnEndWithdrawListings);
            }
            if ((this.onWithdrawListingsCompletedDelegate == null)) {
                this.onWithdrawListingsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnWithdrawListingsCompleted);
            }
            base.InvokeAsync(this.onBeginWithdrawListingsDelegate, new object[] {
                        APICredentials,
                        accountID,
                        skuList,
                        listingIDList,
                        withdrawReason}, this.onEndWithdrawListingsDelegate, this.onWithdrawListingsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChannelAdvisorAccess.ListingService.PingResponse ChannelAdvisorAccess.ListingService.ListingServiceSoap.Ping(ChannelAdvisorAccess.ListingService.PingRequest request) {
            return base.Channel.Ping(request);
        }
        
        public ChannelAdvisorAccess.ListingService.APIResultOfString Ping(ChannelAdvisorAccess.ListingService.APICredentials APICredentials) {
            ChannelAdvisorAccess.ListingService.PingRequest inValue = new ChannelAdvisorAccess.ListingService.PingRequest();
            inValue.APICredentials = APICredentials;
            ChannelAdvisorAccess.ListingService.PingResponse retVal = ((ChannelAdvisorAccess.ListingService.ListingServiceSoap)(this)).Ping(inValue);
            return retVal.PingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ChannelAdvisorAccess.ListingService.ListingServiceSoap.BeginPing(ChannelAdvisorAccess.ListingService.PingRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPing(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginPing(ChannelAdvisorAccess.ListingService.APICredentials APICredentials, System.AsyncCallback callback, object asyncState) {
            ChannelAdvisorAccess.ListingService.PingRequest inValue = new ChannelAdvisorAccess.ListingService.PingRequest();
            inValue.APICredentials = APICredentials;
            return ((ChannelAdvisorAccess.ListingService.ListingServiceSoap)(this)).BeginPing(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChannelAdvisorAccess.ListingService.PingResponse ChannelAdvisorAccess.ListingService.ListingServiceSoap.EndPing(System.IAsyncResult result) {
            return base.Channel.EndPing(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ChannelAdvisorAccess.ListingService.APIResultOfString EndPing(System.IAsyncResult result) {
            ChannelAdvisorAccess.ListingService.PingResponse retVal = ((ChannelAdvisorAccess.ListingService.ListingServiceSoap)(this)).EndPing(result);
            return retVal.PingResult;
        }
        
        private System.IAsyncResult OnBeginPing(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ChannelAdvisorAccess.ListingService.APICredentials APICredentials = ((ChannelAdvisorAccess.ListingService.APICredentials)(inValues[0]));
            return this.BeginPing(APICredentials, callback, asyncState);
        }
        
        private object[] OnEndPing(System.IAsyncResult result) {
            ChannelAdvisorAccess.ListingService.APIResultOfString retVal = this.EndPing(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPingCompleted(object state) {
            if ((this.PingCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PingCompleted(this, new PingCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PingAsync(ChannelAdvisorAccess.ListingService.APICredentials APICredentials) {
            this.PingAsync(APICredentials, null);
        }
        
        public void PingAsync(ChannelAdvisorAccess.ListingService.APICredentials APICredentials, object userState) {
            if ((this.onBeginPingDelegate == null)) {
                this.onBeginPingDelegate = new BeginOperationDelegate(this.OnBeginPing);
            }
            if ((this.onEndPingDelegate == null)) {
                this.onEndPingDelegate = new EndOperationDelegate(this.OnEndPing);
            }
            if ((this.onPingCompletedDelegate == null)) {
                this.onPingCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPingCompleted);
            }
            base.InvokeAsync(this.onBeginPingDelegate, new object[] {
                        APICredentials}, this.onEndPingDelegate, this.onPingCompletedDelegate, userState);
        }
    }
}
