//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannelAdvisorAccess.ShippingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.channeladvisor.com/webservices/", ConfigurationName="ShippingService.ShippingServiceSoap")]
    public interface ShippingServiceSoap {
        
        // CODEGEN: Generating message contract since message GetShippingRateListRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://api.channeladvisor.com/webservices/GetShippingRateList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ChannelAdvisorAccess.ShippingService.GetShippingRateListResponse GetShippingRateList(ChannelAdvisorAccess.ShippingService.GetShippingRateListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.channeladvisor.com/webservices/GetShippingRateList", ReplyAction="*")]
        System.Threading.Tasks.Task<ChannelAdvisorAccess.ShippingService.GetShippingRateListResponse> GetShippingRateListAsync(ChannelAdvisorAccess.ShippingService.GetShippingRateListRequest request);
        
        // CODEGEN: Generating message contract since message GetShippingCarrierListRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://api.channeladvisor.com/webservices/GetShippingCarrierList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ChannelAdvisorAccess.ShippingService.GetShippingCarrierListResponse GetShippingCarrierList(ChannelAdvisorAccess.ShippingService.GetShippingCarrierListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.channeladvisor.com/webservices/GetShippingCarrierList", ReplyAction="*")]
        System.Threading.Tasks.Task<ChannelAdvisorAccess.ShippingService.GetShippingCarrierListResponse> GetShippingCarrierListAsync(ChannelAdvisorAccess.ShippingService.GetShippingCarrierListRequest request);
        
        // CODEGEN: Generating message contract since message GetOrderShipmentHistoryListRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://api.channeladvisor.com/webservices/GetOrderShipmentHistoryList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ChannelAdvisorAccess.ShippingService.GetOrderShipmentHistoryListResponse GetOrderShipmentHistoryList(ChannelAdvisorAccess.ShippingService.GetOrderShipmentHistoryListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.channeladvisor.com/webservices/GetOrderShipmentHistoryList", ReplyAction="*")]
        System.Threading.Tasks.Task<ChannelAdvisorAccess.ShippingService.GetOrderShipmentHistoryListResponse> GetOrderShipmentHistoryListAsync(ChannelAdvisorAccess.ShippingService.GetOrderShipmentHistoryListRequest request);
        
        // CODEGEN: Generating message contract since message SubmitOrderShipmentListRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://api.channeladvisor.com/webservices/SubmitOrderShipmentList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ChannelAdvisorAccess.ShippingService.SubmitOrderShipmentListResponse SubmitOrderShipmentList(ChannelAdvisorAccess.ShippingService.SubmitOrderShipmentListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.channeladvisor.com/webservices/SubmitOrderShipmentList", ReplyAction="*")]
        System.Threading.Tasks.Task<ChannelAdvisorAccess.ShippingService.SubmitOrderShipmentListResponse> SubmitOrderShipmentListAsync(ChannelAdvisorAccess.ShippingService.SubmitOrderShipmentListRequest request);
        
        // CODEGEN: Generating message contract since message PingRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://api.channeladvisor.com/webservices/Ping", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ChannelAdvisorAccess.ShippingService.PingResponse Ping(ChannelAdvisorAccess.ShippingService.PingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.channeladvisor.com/webservices/Ping", ReplyAction="*")]
        System.Threading.Tasks.Task<ChannelAdvisorAccess.ShippingService.PingResponse> PingAsync(ChannelAdvisorAccess.ShippingService.PingRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class APICredentials : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string developerKeyField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DeveloperKey {
            get {
                return this.developerKeyField;
            }
            set {
                this.developerKeyField = value;
                this.RaisePropertyChanged("DeveloperKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class APIResultOfString : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultStatus statusField;
        
        private int messageCodeField;
        
        private string messageField;
        
        private string dataField;
        
        private string resultDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResultStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int MessageCode {
            get {
                return this.messageCodeField;
            }
            set {
                this.messageCodeField = value;
                this.RaisePropertyChanged("MessageCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ResultData {
            get {
                return this.resultDataField;
            }
            set {
                this.resultDataField = value;
                this.RaisePropertyChanged("ResultData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public enum ResultStatus {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Failure,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/datacontracts/ShippingService")]
    public partial class ShipmentResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class APIResultOfArrayOfShipmentResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultStatus statusField;
        
        private int messageCodeField;
        
        private string messageField;
        
        private string dataField;
        
        private ShipmentResponse[] resultDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResultStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int MessageCode {
            get {
                return this.messageCodeField;
            }
            set {
                this.messageCodeField = value;
                this.RaisePropertyChanged("MessageCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public ShipmentResponse[] ResultData {
            get {
                return this.resultDataField;
            }
            set {
                this.resultDataField = value;
                this.RaisePropertyChanged("ResultData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class FullShipmentContents : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<System.DateTime> dateShippedGMTField;
        
        private string carrierCodeField;
        
        private string classCodeField;
        
        private string trackingNumberField;
        
        private string sellerFulfillmentIDField;
        
        private System.Nullable<decimal> shipmentCostField;
        
        private System.Nullable<decimal> shipmentTaxCostField;
        
        private System.Nullable<decimal> insuranceCostField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<System.DateTime> DateShippedGMT {
            get {
                return this.dateShippedGMTField;
            }
            set {
                this.dateShippedGMTField = value;
                this.RaisePropertyChanged("DateShippedGMT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CarrierCode {
            get {
                return this.carrierCodeField;
            }
            set {
                this.carrierCodeField = value;
                this.RaisePropertyChanged("CarrierCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ClassCode {
            get {
                return this.classCodeField;
            }
            set {
                this.classCodeField = value;
                this.RaisePropertyChanged("ClassCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TrackingNumber {
            get {
                return this.trackingNumberField;
            }
            set {
                this.trackingNumberField = value;
                this.RaisePropertyChanged("TrackingNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SellerFulfillmentID {
            get {
                return this.sellerFulfillmentIDField;
            }
            set {
                this.sellerFulfillmentIDField = value;
                this.RaisePropertyChanged("SellerFulfillmentID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<decimal> ShipmentCost {
            get {
                return this.shipmentCostField;
            }
            set {
                this.shipmentCostField = value;
                this.RaisePropertyChanged("ShipmentCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<decimal> ShipmentTaxCost {
            get {
                return this.shipmentTaxCostField;
            }
            set {
                this.shipmentTaxCostField = value;
                this.RaisePropertyChanged("ShipmentTaxCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<decimal> InsuranceCost {
            get {
                return this.insuranceCostField;
            }
            set {
                this.insuranceCostField = value;
                this.RaisePropertyChanged("InsuranceCost");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class LineItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sKUField;
        
        private int quantityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SKU {
            get {
                return this.sKUField;
            }
            set {
                this.sKUField = value;
                this.RaisePropertyChanged("SKU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class PartialShipmentContents : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LineItem[] lineItemListField;
        
        private System.Nullable<System.DateTime> dateShippedGMTField;
        
        private string carrierCodeField;
        
        private string classCodeField;
        
        private string trackingNumberField;
        
        private string sellerFulfillmentIDField;
        
        private System.Nullable<decimal> shipmentCostField;
        
        private System.Nullable<decimal> shipmentTaxCostField;
        
        private System.Nullable<decimal> insuranceCostField;
        
        private string fulfillmentTypeField;
        
        private string fulfillmentStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LineItemList", IsNullable=true, Order=0)]
        public LineItem[] LineItemList {
            get {
                return this.lineItemListField;
            }
            set {
                this.lineItemListField = value;
                this.RaisePropertyChanged("LineItemList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> DateShippedGMT {
            get {
                return this.dateShippedGMTField;
            }
            set {
                this.dateShippedGMTField = value;
                this.RaisePropertyChanged("DateShippedGMT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CarrierCode {
            get {
                return this.carrierCodeField;
            }
            set {
                this.carrierCodeField = value;
                this.RaisePropertyChanged("CarrierCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ClassCode {
            get {
                return this.classCodeField;
            }
            set {
                this.classCodeField = value;
                this.RaisePropertyChanged("ClassCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TrackingNumber {
            get {
                return this.trackingNumberField;
            }
            set {
                this.trackingNumberField = value;
                this.RaisePropertyChanged("TrackingNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SellerFulfillmentID {
            get {
                return this.sellerFulfillmentIDField;
            }
            set {
                this.sellerFulfillmentIDField = value;
                this.RaisePropertyChanged("SellerFulfillmentID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<decimal> ShipmentCost {
            get {
                return this.shipmentCostField;
            }
            set {
                this.shipmentCostField = value;
                this.RaisePropertyChanged("ShipmentCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<decimal> ShipmentTaxCost {
            get {
                return this.shipmentTaxCostField;
            }
            set {
                this.shipmentTaxCostField = value;
                this.RaisePropertyChanged("ShipmentTaxCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<decimal> InsuranceCost {
            get {
                return this.insuranceCostField;
            }
            set {
                this.insuranceCostField = value;
                this.RaisePropertyChanged("InsuranceCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string FulfillmentType {
            get {
                return this.fulfillmentTypeField;
            }
            set {
                this.fulfillmentTypeField = value;
                this.RaisePropertyChanged("FulfillmentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string FulfillmentStatus {
            get {
                return this.fulfillmentStatusField;
            }
            set {
                this.fulfillmentStatusField = value;
                this.RaisePropertyChanged("FulfillmentStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class OrderShipment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> orderIDField;
        
        private string clientOrderIdentifierField;
        
        private string shipmentTypeField;
        
        private PartialShipmentContents partialShipmentField;
        
        private FullShipmentContents fullShipmentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> OrderID {
            get {
                return this.orderIDField;
            }
            set {
                this.orderIDField = value;
                this.RaisePropertyChanged("OrderID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ClientOrderIdentifier {
            get {
                return this.clientOrderIdentifierField;
            }
            set {
                this.clientOrderIdentifierField = value;
                this.RaisePropertyChanged("ClientOrderIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ShipmentType {
            get {
                return this.shipmentTypeField;
            }
            set {
                this.shipmentTypeField = value;
                this.RaisePropertyChanged("ShipmentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public PartialShipmentContents PartialShipment {
            get {
                return this.partialShipmentField;
            }
            set {
                this.partialShipmentField = value;
                this.RaisePropertyChanged("PartialShipment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public FullShipmentContents FullShipment {
            get {
                return this.fullShipmentField;
            }
            set {
                this.fullShipmentField = value;
                this.RaisePropertyChanged("FullShipment");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/datacontracts/ShippingService")]
    public partial class ShipmentLineItemResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int lineItemIDField;
        
        private string sKUField;
        
        private int quantityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int LineItemID {
            get {
                return this.lineItemIDField;
            }
            set {
                this.lineItemIDField = value;
                this.RaisePropertyChanged("LineItemID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SKU {
            get {
                return this.sKUField;
            }
            set {
                this.sKUField = value;
                this.RaisePropertyChanged("SKU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/datacontracts/ShippingService")]
    public partial class OrderShipmentResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime shipmentDateGMTField;
        
        private string carrierCodeField;
        
        private string classCodeField;
        
        private string trackingNumberField;
        
        private string distributionCenterCodeField;
        
        private decimal shipmentCostField;
        
        private decimal shipmentTaxCostField;
        
        private decimal shipmentInsuranceCostField;
        
        private string sellerFulfillmentIDField;
        
        private ShipmentLineItemResponse[] shipmentLineItemsField;
        
        private string fulfillmentTypeField;
        
        private string fulfillmentStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime ShipmentDateGMT {
            get {
                return this.shipmentDateGMTField;
            }
            set {
                this.shipmentDateGMTField = value;
                this.RaisePropertyChanged("ShipmentDateGMT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CarrierCode {
            get {
                return this.carrierCodeField;
            }
            set {
                this.carrierCodeField = value;
                this.RaisePropertyChanged("CarrierCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ClassCode {
            get {
                return this.classCodeField;
            }
            set {
                this.classCodeField = value;
                this.RaisePropertyChanged("ClassCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TrackingNumber {
            get {
                return this.trackingNumberField;
            }
            set {
                this.trackingNumberField = value;
                this.RaisePropertyChanged("TrackingNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DistributionCenterCode {
            get {
                return this.distributionCenterCodeField;
            }
            set {
                this.distributionCenterCodeField = value;
                this.RaisePropertyChanged("DistributionCenterCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal ShipmentCost {
            get {
                return this.shipmentCostField;
            }
            set {
                this.shipmentCostField = value;
                this.RaisePropertyChanged("ShipmentCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal ShipmentTaxCost {
            get {
                return this.shipmentTaxCostField;
            }
            set {
                this.shipmentTaxCostField = value;
                this.RaisePropertyChanged("ShipmentTaxCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal ShipmentInsuranceCost {
            get {
                return this.shipmentInsuranceCostField;
            }
            set {
                this.shipmentInsuranceCostField = value;
                this.RaisePropertyChanged("ShipmentInsuranceCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string SellerFulfillmentID {
            get {
                return this.sellerFulfillmentIDField;
            }
            set {
                this.sellerFulfillmentIDField = value;
                this.RaisePropertyChanged("SellerFulfillmentID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        public ShipmentLineItemResponse[] ShipmentLineItems {
            get {
                return this.shipmentLineItemsField;
            }
            set {
                this.shipmentLineItemsField = value;
                this.RaisePropertyChanged("ShipmentLineItems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string FulfillmentType {
            get {
                return this.fulfillmentTypeField;
            }
            set {
                this.fulfillmentTypeField = value;
                this.RaisePropertyChanged("FulfillmentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string FulfillmentStatus {
            get {
                return this.fulfillmentStatusField;
            }
            set {
                this.fulfillmentStatusField = value;
                this.RaisePropertyChanged("FulfillmentStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/datacontracts/ShippingService")]
    public partial class OrderShipmentHistoryResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int orderIDField;
        
        private string clientOrderIdentifierField;
        
        private string shippingStatusField;
        
        private System.DateTime shippingStatusUpdateDateGMTField;
        
        private OrderShipmentResponse[] orderShipmentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int OrderID {
            get {
                return this.orderIDField;
            }
            set {
                this.orderIDField = value;
                this.RaisePropertyChanged("OrderID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ClientOrderIdentifier {
            get {
                return this.clientOrderIdentifierField;
            }
            set {
                this.clientOrderIdentifierField = value;
                this.RaisePropertyChanged("ClientOrderIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ShippingStatus {
            get {
                return this.shippingStatusField;
            }
            set {
                this.shippingStatusField = value;
                this.RaisePropertyChanged("ShippingStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime ShippingStatusUpdateDateGMT {
            get {
                return this.shippingStatusUpdateDateGMTField;
            }
            set {
                this.shippingStatusUpdateDateGMTField = value;
                this.RaisePropertyChanged("ShippingStatusUpdateDateGMT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public OrderShipmentResponse[] OrderShipments {
            get {
                return this.orderShipmentsField;
            }
            set {
                this.orderShipmentsField = value;
                this.RaisePropertyChanged("OrderShipments");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class APIResultOfArrayOfOrderShipmentHistoryResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultStatus statusField;
        
        private int messageCodeField;
        
        private string messageField;
        
        private string dataField;
        
        private OrderShipmentHistoryResponse[] resultDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResultStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int MessageCode {
            get {
                return this.messageCodeField;
            }
            set {
                this.messageCodeField = value;
                this.RaisePropertyChanged("MessageCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public OrderShipmentHistoryResponse[] ResultData {
            get {
                return this.resultDataField;
            }
            set {
                this.resultDataField = value;
                this.RaisePropertyChanged("ResultData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class ShippingCarrier : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int carrierIDField;
        
        private int classIDField;
        
        private string carrierNameField;
        
        private string carrierCodeField;
        
        private string classCodeField;
        
        private string classNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CarrierID {
            get {
                return this.carrierIDField;
            }
            set {
                this.carrierIDField = value;
                this.RaisePropertyChanged("CarrierID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ClassID {
            get {
                return this.classIDField;
            }
            set {
                this.classIDField = value;
                this.RaisePropertyChanged("ClassID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CarrierName {
            get {
                return this.carrierNameField;
            }
            set {
                this.carrierNameField = value;
                this.RaisePropertyChanged("CarrierName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CarrierCode {
            get {
                return this.carrierCodeField;
            }
            set {
                this.carrierCodeField = value;
                this.RaisePropertyChanged("CarrierCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ClassCode {
            get {
                return this.classCodeField;
            }
            set {
                this.classCodeField = value;
                this.RaisePropertyChanged("ClassCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ClassName {
            get {
                return this.classNameField;
            }
            set {
                this.classNameField = value;
                this.RaisePropertyChanged("ClassName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class APIResultOfArrayOfShippingCarrier : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultStatus statusField;
        
        private int messageCodeField;
        
        private string messageField;
        
        private string dataField;
        
        private ShippingCarrier[] resultDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResultStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int MessageCode {
            get {
                return this.messageCodeField;
            }
            set {
                this.messageCodeField = value;
                this.RaisePropertyChanged("MessageCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public ShippingCarrier[] ResultData {
            get {
                return this.resultDataField;
            }
            set {
                this.resultDataField = value;
                this.RaisePropertyChanged("ResultData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class ShippingItemBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string carrierNameField;
        
        private string classNameField;
        
        private decimal shippingCostField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CarrierName {
            get {
                return this.carrierNameField;
            }
            set {
                this.carrierNameField = value;
                this.RaisePropertyChanged("CarrierName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ClassName {
            get {
                return this.classNameField;
            }
            set {
                this.classNameField = value;
                this.RaisePropertyChanged("ClassName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal ShippingCost {
            get {
                return this.shippingCostField;
            }
            set {
                this.shippingCostField = value;
                this.RaisePropertyChanged("ShippingCost");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class ShippingRateResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ShippingItemBase[] shippingDetailListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public ShippingItemBase[] ShippingDetailList {
            get {
                return this.shippingDetailListField;
            }
            set {
                this.shippingDetailListField = value;
                this.RaisePropertyChanged("ShippingDetailList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class APIResultOfShippingRateResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultStatus statusField;
        
        private int messageCodeField;
        
        private string messageField;
        
        private string dataField;
        
        private ShippingRateResult resultDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResultStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int MessageCode {
            get {
                return this.messageCodeField;
            }
            set {
                this.messageCodeField = value;
                this.RaisePropertyChanged("MessageCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public ShippingRateResult ResultData {
            get {
                return this.resultDataField;
            }
            set {
                this.resultDataField = value;
                this.RaisePropertyChanged("ResultData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetShippingRateList", WrapperNamespace="http://api.channeladvisor.com/webservices/", IsWrapped=true)]
    public partial class GetShippingRateListRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
        public ChannelAdvisorAccess.ShippingService.APICredentials APICredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string accountID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=1)]
        public int cartID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=2)]
        public string street;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=3)]
        public string city;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=4)]
        public string state;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=5)]
        public string postalCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string country;
        
        public GetShippingRateListRequest() {
        }
        
        public GetShippingRateListRequest(ChannelAdvisorAccess.ShippingService.APICredentials APICredentials, string accountID, int cartID, string street, string city, string state, string postalCode, string country) {
            this.APICredentials = APICredentials;
            this.accountID = accountID;
            this.cartID = cartID;
            this.street = street;
            this.city = city;
            this.state = state;
            this.postalCode = postalCode;
            this.country = country;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetShippingRateListResponse", WrapperNamespace="http://api.channeladvisor.com/webservices/", IsWrapped=true)]
    public partial class GetShippingRateListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=0)]
        public ChannelAdvisorAccess.ShippingService.APIResultOfShippingRateResult GetShippingRateListResult;
        
        public GetShippingRateListResponse() {
        }
        
        public GetShippingRateListResponse(ChannelAdvisorAccess.ShippingService.APIResultOfShippingRateResult GetShippingRateListResult) {
            this.GetShippingRateListResult = GetShippingRateListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetShippingCarrierList", WrapperNamespace="http://api.channeladvisor.com/webservices/", IsWrapped=true)]
    public partial class GetShippingCarrierListRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
        public ChannelAdvisorAccess.ShippingService.APICredentials APICredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string accountID;
        
        public GetShippingCarrierListRequest() {
        }
        
        public GetShippingCarrierListRequest(ChannelAdvisorAccess.ShippingService.APICredentials APICredentials, string accountID) {
            this.APICredentials = APICredentials;
            this.accountID = accountID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetShippingCarrierListResponse", WrapperNamespace="http://api.channeladvisor.com/webservices/", IsWrapped=true)]
    public partial class GetShippingCarrierListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=0)]
        public ChannelAdvisorAccess.ShippingService.APIResultOfArrayOfShippingCarrier GetShippingCarrierListResult;
        
        public GetShippingCarrierListResponse() {
        }
        
        public GetShippingCarrierListResponse(ChannelAdvisorAccess.ShippingService.APIResultOfArrayOfShippingCarrier GetShippingCarrierListResult) {
            this.GetShippingCarrierListResult = GetShippingCarrierListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOrderShipmentHistoryList", WrapperNamespace="http://api.channeladvisor.com/webservices/", IsWrapped=true)]
    public partial class GetOrderShipmentHistoryListRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
        public ChannelAdvisorAccess.ShippingService.APICredentials APICredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string accountID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=1)]
        public int[] orderIDList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=2)]
        public string[] clientOrderIdentifierList;
        
        public GetOrderShipmentHistoryListRequest() {
        }
        
        public GetOrderShipmentHistoryListRequest(ChannelAdvisorAccess.ShippingService.APICredentials APICredentials, string accountID, int[] orderIDList, string[] clientOrderIdentifierList) {
            this.APICredentials = APICredentials;
            this.accountID = accountID;
            this.orderIDList = orderIDList;
            this.clientOrderIdentifierList = clientOrderIdentifierList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOrderShipmentHistoryListResponse", WrapperNamespace="http://api.channeladvisor.com/webservices/", IsWrapped=true)]
    public partial class GetOrderShipmentHistoryListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=0)]
        public ChannelAdvisorAccess.ShippingService.APIResultOfArrayOfOrderShipmentHistoryResponse GetOrderShipmentHistoryListResult;
        
        public GetOrderShipmentHistoryListResponse() {
        }
        
        public GetOrderShipmentHistoryListResponse(ChannelAdvisorAccess.ShippingService.APIResultOfArrayOfOrderShipmentHistoryResponse GetOrderShipmentHistoryListResult) {
            this.GetOrderShipmentHistoryListResult = GetOrderShipmentHistoryListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitOrderShipmentList", WrapperNamespace="http://api.channeladvisor.com/webservices/", IsWrapped=true)]
    public partial class SubmitOrderShipmentListRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
        public ChannelAdvisorAccess.ShippingService.APICredentials APICredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string accountID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("shipmentList", IsNullable=true)]
        public ChannelAdvisorAccess.ShippingService.OrderShipment[] shipmentList;
        
        public SubmitOrderShipmentListRequest() {
        }
        
        public SubmitOrderShipmentListRequest(ChannelAdvisorAccess.ShippingService.APICredentials APICredentials, string accountID, ChannelAdvisorAccess.ShippingService.OrderShipment[] shipmentList) {
            this.APICredentials = APICredentials;
            this.accountID = accountID;
            this.shipmentList = shipmentList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitOrderShipmentListResponse", WrapperNamespace="http://api.channeladvisor.com/webservices/", IsWrapped=true)]
    public partial class SubmitOrderShipmentListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=0)]
        public ChannelAdvisorAccess.ShippingService.APIResultOfArrayOfShipmentResponse SubmitOrderShipmentListResult;
        
        public SubmitOrderShipmentListResponse() {
        }
        
        public SubmitOrderShipmentListResponse(ChannelAdvisorAccess.ShippingService.APIResultOfArrayOfShipmentResponse SubmitOrderShipmentListResult) {
            this.SubmitOrderShipmentListResult = SubmitOrderShipmentListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Ping", WrapperNamespace="http://api.channeladvisor.com/webservices/", IsWrapped=true)]
    public partial class PingRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
        public ChannelAdvisorAccess.ShippingService.APICredentials APICredentials;
        
        public PingRequest() {
        }
        
        public PingRequest(ChannelAdvisorAccess.ShippingService.APICredentials APICredentials) {
            this.APICredentials = APICredentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PingResponse", WrapperNamespace="http://api.channeladvisor.com/webservices/", IsWrapped=true)]
    public partial class PingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=0)]
        public ChannelAdvisorAccess.ShippingService.APIResultOfString PingResult;
        
        public PingResponse() {
        }
        
        public PingResponse(ChannelAdvisorAccess.ShippingService.APIResultOfString PingResult) {
            this.PingResult = PingResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ShippingServiceSoapChannel : ChannelAdvisorAccess.ShippingService.ShippingServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShippingServiceSoapClient : System.ServiceModel.ClientBase<ChannelAdvisorAccess.ShippingService.ShippingServiceSoap>, ChannelAdvisorAccess.ShippingService.ShippingServiceSoap {
        
        public ShippingServiceSoapClient() {
        }
        
        public ShippingServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShippingServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShippingServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShippingServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChannelAdvisorAccess.ShippingService.GetShippingRateListResponse ChannelAdvisorAccess.ShippingService.ShippingServiceSoap.GetShippingRateList(ChannelAdvisorAccess.ShippingService.GetShippingRateListRequest request) {
            return base.Channel.GetShippingRateList(request);
        }
        
        public ChannelAdvisorAccess.ShippingService.APIResultOfShippingRateResult GetShippingRateList(ChannelAdvisorAccess.ShippingService.APICredentials APICredentials, string accountID, int cartID, string street, string city, string state, string postalCode, string country) {
            ChannelAdvisorAccess.ShippingService.GetShippingRateListRequest inValue = new ChannelAdvisorAccess.ShippingService.GetShippingRateListRequest();
            inValue.APICredentials = APICredentials;
            inValue.accountID = accountID;
            inValue.cartID = cartID;
            inValue.street = street;
            inValue.city = city;
            inValue.state = state;
            inValue.postalCode = postalCode;
            inValue.country = country;
            ChannelAdvisorAccess.ShippingService.GetShippingRateListResponse retVal = ((ChannelAdvisorAccess.ShippingService.ShippingServiceSoap)(this)).GetShippingRateList(inValue);
            return retVal.GetShippingRateListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ChannelAdvisorAccess.ShippingService.GetShippingRateListResponse> ChannelAdvisorAccess.ShippingService.ShippingServiceSoap.GetShippingRateListAsync(ChannelAdvisorAccess.ShippingService.GetShippingRateListRequest request) {
            return base.Channel.GetShippingRateListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ChannelAdvisorAccess.ShippingService.GetShippingRateListResponse> GetShippingRateListAsync(ChannelAdvisorAccess.ShippingService.APICredentials APICredentials, string accountID, int cartID, string street, string city, string state, string postalCode, string country) {
            ChannelAdvisorAccess.ShippingService.GetShippingRateListRequest inValue = new ChannelAdvisorAccess.ShippingService.GetShippingRateListRequest();
            inValue.APICredentials = APICredentials;
            inValue.accountID = accountID;
            inValue.cartID = cartID;
            inValue.street = street;
            inValue.city = city;
            inValue.state = state;
            inValue.postalCode = postalCode;
            inValue.country = country;
            return ((ChannelAdvisorAccess.ShippingService.ShippingServiceSoap)(this)).GetShippingRateListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChannelAdvisorAccess.ShippingService.GetShippingCarrierListResponse ChannelAdvisorAccess.ShippingService.ShippingServiceSoap.GetShippingCarrierList(ChannelAdvisorAccess.ShippingService.GetShippingCarrierListRequest request) {
            return base.Channel.GetShippingCarrierList(request);
        }
        
        public ChannelAdvisorAccess.ShippingService.APIResultOfArrayOfShippingCarrier GetShippingCarrierList(ChannelAdvisorAccess.ShippingService.APICredentials APICredentials, string accountID) {
            ChannelAdvisorAccess.ShippingService.GetShippingCarrierListRequest inValue = new ChannelAdvisorAccess.ShippingService.GetShippingCarrierListRequest();
            inValue.APICredentials = APICredentials;
            inValue.accountID = accountID;
            ChannelAdvisorAccess.ShippingService.GetShippingCarrierListResponse retVal = ((ChannelAdvisorAccess.ShippingService.ShippingServiceSoap)(this)).GetShippingCarrierList(inValue);
            return retVal.GetShippingCarrierListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ChannelAdvisorAccess.ShippingService.GetShippingCarrierListResponse> ChannelAdvisorAccess.ShippingService.ShippingServiceSoap.GetShippingCarrierListAsync(ChannelAdvisorAccess.ShippingService.GetShippingCarrierListRequest request) {
            return base.Channel.GetShippingCarrierListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ChannelAdvisorAccess.ShippingService.GetShippingCarrierListResponse> GetShippingCarrierListAsync(ChannelAdvisorAccess.ShippingService.APICredentials APICredentials, string accountID) {
            ChannelAdvisorAccess.ShippingService.GetShippingCarrierListRequest inValue = new ChannelAdvisorAccess.ShippingService.GetShippingCarrierListRequest();
            inValue.APICredentials = APICredentials;
            inValue.accountID = accountID;
            return ((ChannelAdvisorAccess.ShippingService.ShippingServiceSoap)(this)).GetShippingCarrierListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChannelAdvisorAccess.ShippingService.GetOrderShipmentHistoryListResponse ChannelAdvisorAccess.ShippingService.ShippingServiceSoap.GetOrderShipmentHistoryList(ChannelAdvisorAccess.ShippingService.GetOrderShipmentHistoryListRequest request) {
            return base.Channel.GetOrderShipmentHistoryList(request);
        }
        
        public ChannelAdvisorAccess.ShippingService.APIResultOfArrayOfOrderShipmentHistoryResponse GetOrderShipmentHistoryList(ChannelAdvisorAccess.ShippingService.APICredentials APICredentials, string accountID, int[] orderIDList, string[] clientOrderIdentifierList) {
            ChannelAdvisorAccess.ShippingService.GetOrderShipmentHistoryListRequest inValue = new ChannelAdvisorAccess.ShippingService.GetOrderShipmentHistoryListRequest();
            inValue.APICredentials = APICredentials;
            inValue.accountID = accountID;
            inValue.orderIDList = orderIDList;
            inValue.clientOrderIdentifierList = clientOrderIdentifierList;
            ChannelAdvisorAccess.ShippingService.GetOrderShipmentHistoryListResponse retVal = ((ChannelAdvisorAccess.ShippingService.ShippingServiceSoap)(this)).GetOrderShipmentHistoryList(inValue);
            return retVal.GetOrderShipmentHistoryListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ChannelAdvisorAccess.ShippingService.GetOrderShipmentHistoryListResponse> ChannelAdvisorAccess.ShippingService.ShippingServiceSoap.GetOrderShipmentHistoryListAsync(ChannelAdvisorAccess.ShippingService.GetOrderShipmentHistoryListRequest request) {
            return base.Channel.GetOrderShipmentHistoryListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ChannelAdvisorAccess.ShippingService.GetOrderShipmentHistoryListResponse> GetOrderShipmentHistoryListAsync(ChannelAdvisorAccess.ShippingService.APICredentials APICredentials, string accountID, int[] orderIDList, string[] clientOrderIdentifierList) {
            ChannelAdvisorAccess.ShippingService.GetOrderShipmentHistoryListRequest inValue = new ChannelAdvisorAccess.ShippingService.GetOrderShipmentHistoryListRequest();
            inValue.APICredentials = APICredentials;
            inValue.accountID = accountID;
            inValue.orderIDList = orderIDList;
            inValue.clientOrderIdentifierList = clientOrderIdentifierList;
            return ((ChannelAdvisorAccess.ShippingService.ShippingServiceSoap)(this)).GetOrderShipmentHistoryListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChannelAdvisorAccess.ShippingService.SubmitOrderShipmentListResponse ChannelAdvisorAccess.ShippingService.ShippingServiceSoap.SubmitOrderShipmentList(ChannelAdvisorAccess.ShippingService.SubmitOrderShipmentListRequest request) {
            return base.Channel.SubmitOrderShipmentList(request);
        }
        
        public ChannelAdvisorAccess.ShippingService.APIResultOfArrayOfShipmentResponse SubmitOrderShipmentList(ChannelAdvisorAccess.ShippingService.APICredentials APICredentials, string accountID, ChannelAdvisorAccess.ShippingService.OrderShipment[] shipmentList) {
            ChannelAdvisorAccess.ShippingService.SubmitOrderShipmentListRequest inValue = new ChannelAdvisorAccess.ShippingService.SubmitOrderShipmentListRequest();
            inValue.APICredentials = APICredentials;
            inValue.accountID = accountID;
            inValue.shipmentList = shipmentList;
            ChannelAdvisorAccess.ShippingService.SubmitOrderShipmentListResponse retVal = ((ChannelAdvisorAccess.ShippingService.ShippingServiceSoap)(this)).SubmitOrderShipmentList(inValue);
            return retVal.SubmitOrderShipmentListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ChannelAdvisorAccess.ShippingService.SubmitOrderShipmentListResponse> ChannelAdvisorAccess.ShippingService.ShippingServiceSoap.SubmitOrderShipmentListAsync(ChannelAdvisorAccess.ShippingService.SubmitOrderShipmentListRequest request) {
            return base.Channel.SubmitOrderShipmentListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ChannelAdvisorAccess.ShippingService.SubmitOrderShipmentListResponse> SubmitOrderShipmentListAsync(ChannelAdvisorAccess.ShippingService.APICredentials APICredentials, string accountID, ChannelAdvisorAccess.ShippingService.OrderShipment[] shipmentList) {
            ChannelAdvisorAccess.ShippingService.SubmitOrderShipmentListRequest inValue = new ChannelAdvisorAccess.ShippingService.SubmitOrderShipmentListRequest();
            inValue.APICredentials = APICredentials;
            inValue.accountID = accountID;
            inValue.shipmentList = shipmentList;
            return ((ChannelAdvisorAccess.ShippingService.ShippingServiceSoap)(this)).SubmitOrderShipmentListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChannelAdvisorAccess.ShippingService.PingResponse ChannelAdvisorAccess.ShippingService.ShippingServiceSoap.Ping(ChannelAdvisorAccess.ShippingService.PingRequest request) {
            return base.Channel.Ping(request);
        }
        
        public ChannelAdvisorAccess.ShippingService.APIResultOfString Ping(ChannelAdvisorAccess.ShippingService.APICredentials APICredentials) {
            ChannelAdvisorAccess.ShippingService.PingRequest inValue = new ChannelAdvisorAccess.ShippingService.PingRequest();
            inValue.APICredentials = APICredentials;
            ChannelAdvisorAccess.ShippingService.PingResponse retVal = ((ChannelAdvisorAccess.ShippingService.ShippingServiceSoap)(this)).Ping(inValue);
            return retVal.PingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ChannelAdvisorAccess.ShippingService.PingResponse> ChannelAdvisorAccess.ShippingService.ShippingServiceSoap.PingAsync(ChannelAdvisorAccess.ShippingService.PingRequest request) {
            return base.Channel.PingAsync(request);
        }
        
        public System.Threading.Tasks.Task<ChannelAdvisorAccess.ShippingService.PingResponse> PingAsync(ChannelAdvisorAccess.ShippingService.APICredentials APICredentials) {
            ChannelAdvisorAccess.ShippingService.PingRequest inValue = new ChannelAdvisorAccess.ShippingService.PingRequest();
            inValue.APICredentials = APICredentials;
            return ((ChannelAdvisorAccess.ShippingService.ShippingServiceSoap)(this)).PingAsync(inValue);
        }
    }
}
