//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannelAdvisorAccess.AdminService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.channeladvisor.com/webservices/", ConfigurationName="AdminService.AdminServiceSoap")]
    public interface AdminServiceSoap {
        
        // CODEGEN: Generating message contract since message GetAuthorizationListRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://api.channeladvisor.com/webservices/GetAuthorizationList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ChannelAdvisorAccess.AdminService.GetAuthorizationListResponse GetAuthorizationList(ChannelAdvisorAccess.AdminService.GetAuthorizationListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://api.channeladvisor.com/webservices/GetAuthorizationList", ReplyAction="*")]
        System.IAsyncResult BeginGetAuthorizationList(ChannelAdvisorAccess.AdminService.GetAuthorizationListRequest request, System.AsyncCallback callback, object asyncState);
        
        ChannelAdvisorAccess.AdminService.GetAuthorizationListResponse EndGetAuthorizationList(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since message RequestAccessRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://api.channeladvisor.com/webservices/RequestAccess", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ChannelAdvisorAccess.AdminService.RequestAccessResponse RequestAccess(ChannelAdvisorAccess.AdminService.RequestAccessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://api.channeladvisor.com/webservices/RequestAccess", ReplyAction="*")]
        System.IAsyncResult BeginRequestAccess(ChannelAdvisorAccess.AdminService.RequestAccessRequest request, System.AsyncCallback callback, object asyncState);
        
        ChannelAdvisorAccess.AdminService.RequestAccessResponse EndRequestAccess(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since message PingRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://api.channeladvisor.com/webservices/Ping", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ChannelAdvisorAccess.AdminService.PingResponse Ping(ChannelAdvisorAccess.AdminService.PingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://api.channeladvisor.com/webservices/Ping", ReplyAction="*")]
        System.IAsyncResult BeginPing(ChannelAdvisorAccess.AdminService.PingRequest request, System.AsyncCallback callback, object asyncState);
        
        ChannelAdvisorAccess.AdminService.PingResponse EndPing(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class APICredentials : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string developerKeyField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DeveloperKey {
            get {
                return this.developerKeyField;
            }
            set {
                this.developerKeyField = value;
                this.RaisePropertyChanged("DeveloperKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class APIResultOfString : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultStatus statusField;
        
        private int messageCodeField;
        
        private string messageField;
        
        private string dataField;
        
        private string resultDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResultStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int MessageCode {
            get {
                return this.messageCodeField;
            }
            set {
                this.messageCodeField = value;
                this.RaisePropertyChanged("MessageCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ResultData {
            get {
                return this.resultDataField;
            }
            set {
                this.resultDataField = value;
                this.RaisePropertyChanged("ResultData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public enum ResultStatus {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Failure,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class APIResultOfBoolean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultStatus statusField;
        
        private int messageCodeField;
        
        private string messageField;
        
        private string dataField;
        
        private bool resultDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResultStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int MessageCode {
            get {
                return this.messageCodeField;
            }
            set {
                this.messageCodeField = value;
                this.RaisePropertyChanged("MessageCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool ResultData {
            get {
                return this.resultDataField;
            }
            set {
                this.resultDataField = value;
                this.RaisePropertyChanged("ResultData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class AuthorizationResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accountIDField;
        
        private int localIDField;
        
        private string accountNameField;
        
        private string accountTypeField;
        
        private string resourceNameField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccountID {
            get {
                return this.accountIDField;
            }
            set {
                this.accountIDField = value;
                this.RaisePropertyChanged("AccountID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int LocalID {
            get {
                return this.localIDField;
            }
            set {
                this.localIDField = value;
                this.RaisePropertyChanged("LocalID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AccountName {
            get {
                return this.accountNameField;
            }
            set {
                this.accountNameField = value;
                this.RaisePropertyChanged("AccountName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string AccountType {
            get {
                return this.accountTypeField;
            }
            set {
                this.accountTypeField = value;
                this.RaisePropertyChanged("AccountType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ResourceName {
            get {
                return this.resourceNameField;
            }
            set {
                this.resourceNameField = value;
                this.RaisePropertyChanged("ResourceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class APIResultOfArrayOfAuthorizationResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultStatus statusField;
        
        private int messageCodeField;
        
        private string messageField;
        
        private string dataField;
        
        private AuthorizationResponse[] resultDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResultStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int MessageCode {
            get {
                return this.messageCodeField;
            }
            set {
                this.messageCodeField = value;
                this.RaisePropertyChanged("MessageCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public AuthorizationResponse[] ResultData {
            get {
                return this.resultDataField;
            }
            set {
                this.resultDataField = value;
                this.RaisePropertyChanged("ResultData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAuthorizationList", WrapperNamespace="http://api.channeladvisor.com/webservices/", IsWrapped=true)]
    public partial class GetAuthorizationListRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
        public ChannelAdvisorAccess.AdminService.APICredentials APICredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string localID;
        
        public GetAuthorizationListRequest() {
        }
        
        public GetAuthorizationListRequest(ChannelAdvisorAccess.AdminService.APICredentials APICredentials, string localID) {
            this.APICredentials = APICredentials;
            this.localID = localID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAuthorizationListResponse", WrapperNamespace="http://api.channeladvisor.com/webservices/", IsWrapped=true)]
    public partial class GetAuthorizationListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=0)]
        public ChannelAdvisorAccess.AdminService.APIResultOfArrayOfAuthorizationResponse GetAuthorizationListResult;
        
        public GetAuthorizationListResponse() {
        }
        
        public GetAuthorizationListResponse(ChannelAdvisorAccess.AdminService.APIResultOfArrayOfAuthorizationResponse GetAuthorizationListResult) {
            this.GetAuthorizationListResult = GetAuthorizationListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequestAccess", WrapperNamespace="http://api.channeladvisor.com/webservices/", IsWrapped=true)]
    public partial class RequestAccessRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
        public ChannelAdvisorAccess.AdminService.APICredentials APICredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=0)]
        public int localID;
        
        public RequestAccessRequest() {
        }
        
        public RequestAccessRequest(ChannelAdvisorAccess.AdminService.APICredentials APICredentials, int localID) {
            this.APICredentials = APICredentials;
            this.localID = localID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequestAccessResponse", WrapperNamespace="http://api.channeladvisor.com/webservices/", IsWrapped=true)]
    public partial class RequestAccessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=0)]
        public ChannelAdvisorAccess.AdminService.APIResultOfBoolean RequestAccessResult;
        
        public RequestAccessResponse() {
        }
        
        public RequestAccessResponse(ChannelAdvisorAccess.AdminService.APIResultOfBoolean RequestAccessResult) {
            this.RequestAccessResult = RequestAccessResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Ping", WrapperNamespace="http://api.channeladvisor.com/webservices/", IsWrapped=true)]
    public partial class PingRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
        public ChannelAdvisorAccess.AdminService.APICredentials APICredentials;
        
        public PingRequest() {
        }
        
        public PingRequest(ChannelAdvisorAccess.AdminService.APICredentials APICredentials) {
            this.APICredentials = APICredentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PingResponse", WrapperNamespace="http://api.channeladvisor.com/webservices/", IsWrapped=true)]
    public partial class PingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=0)]
        public ChannelAdvisorAccess.AdminService.APIResultOfString PingResult;
        
        public PingResponse() {
        }
        
        public PingResponse(ChannelAdvisorAccess.AdminService.APIResultOfString PingResult) {
            this.PingResult = PingResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AdminServiceSoapChannel : ChannelAdvisorAccess.AdminService.AdminServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAuthorizationListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAuthorizationListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ChannelAdvisorAccess.AdminService.APIResultOfArrayOfAuthorizationResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ChannelAdvisorAccess.AdminService.APIResultOfArrayOfAuthorizationResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RequestAccessCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RequestAccessCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ChannelAdvisorAccess.AdminService.APIResultOfBoolean Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ChannelAdvisorAccess.AdminService.APIResultOfBoolean)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public PingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ChannelAdvisorAccess.AdminService.APIResultOfString Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ChannelAdvisorAccess.AdminService.APIResultOfString)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminServiceSoapClient : System.ServiceModel.ClientBase<ChannelAdvisorAccess.AdminService.AdminServiceSoap>, ChannelAdvisorAccess.AdminService.AdminServiceSoap {
        
        private BeginOperationDelegate onBeginGetAuthorizationListDelegate;
        
        private EndOperationDelegate onEndGetAuthorizationListDelegate;
        
        private System.Threading.SendOrPostCallback onGetAuthorizationListCompletedDelegate;
        
        private BeginOperationDelegate onBeginRequestAccessDelegate;
        
        private EndOperationDelegate onEndRequestAccessDelegate;
        
        private System.Threading.SendOrPostCallback onRequestAccessCompletedDelegate;
        
        private BeginOperationDelegate onBeginPingDelegate;
        
        private EndOperationDelegate onEndPingDelegate;
        
        private System.Threading.SendOrPostCallback onPingCompletedDelegate;
        
        public AdminServiceSoapClient() {
        }
        
        public AdminServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetAuthorizationListCompletedEventArgs> GetAuthorizationListCompleted;
        
        public event System.EventHandler<RequestAccessCompletedEventArgs> RequestAccessCompleted;
        
        public event System.EventHandler<PingCompletedEventArgs> PingCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChannelAdvisorAccess.AdminService.GetAuthorizationListResponse ChannelAdvisorAccess.AdminService.AdminServiceSoap.GetAuthorizationList(ChannelAdvisorAccess.AdminService.GetAuthorizationListRequest request) {
            return base.Channel.GetAuthorizationList(request);
        }
        
        public ChannelAdvisorAccess.AdminService.APIResultOfArrayOfAuthorizationResponse GetAuthorizationList(ChannelAdvisorAccess.AdminService.APICredentials APICredentials, string localID) {
            ChannelAdvisorAccess.AdminService.GetAuthorizationListRequest inValue = new ChannelAdvisorAccess.AdminService.GetAuthorizationListRequest();
            inValue.APICredentials = APICredentials;
            inValue.localID = localID;
            ChannelAdvisorAccess.AdminService.GetAuthorizationListResponse retVal = ((ChannelAdvisorAccess.AdminService.AdminServiceSoap)(this)).GetAuthorizationList(inValue);
            return retVal.GetAuthorizationListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ChannelAdvisorAccess.AdminService.AdminServiceSoap.BeginGetAuthorizationList(ChannelAdvisorAccess.AdminService.GetAuthorizationListRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAuthorizationList(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetAuthorizationList(ChannelAdvisorAccess.AdminService.APICredentials APICredentials, string localID, System.AsyncCallback callback, object asyncState) {
            ChannelAdvisorAccess.AdminService.GetAuthorizationListRequest inValue = new ChannelAdvisorAccess.AdminService.GetAuthorizationListRequest();
            inValue.APICredentials = APICredentials;
            inValue.localID = localID;
            return ((ChannelAdvisorAccess.AdminService.AdminServiceSoap)(this)).BeginGetAuthorizationList(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChannelAdvisorAccess.AdminService.GetAuthorizationListResponse ChannelAdvisorAccess.AdminService.AdminServiceSoap.EndGetAuthorizationList(System.IAsyncResult result) {
            return base.Channel.EndGetAuthorizationList(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ChannelAdvisorAccess.AdminService.APIResultOfArrayOfAuthorizationResponse EndGetAuthorizationList(System.IAsyncResult result) {
            ChannelAdvisorAccess.AdminService.GetAuthorizationListResponse retVal = ((ChannelAdvisorAccess.AdminService.AdminServiceSoap)(this)).EndGetAuthorizationList(result);
            return retVal.GetAuthorizationListResult;
        }
        
        private System.IAsyncResult OnBeginGetAuthorizationList(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ChannelAdvisorAccess.AdminService.APICredentials APICredentials = ((ChannelAdvisorAccess.AdminService.APICredentials)(inValues[0]));
            string localID = ((string)(inValues[1]));
            return this.BeginGetAuthorizationList(APICredentials, localID, callback, asyncState);
        }
        
        private object[] OnEndGetAuthorizationList(System.IAsyncResult result) {
            ChannelAdvisorAccess.AdminService.APIResultOfArrayOfAuthorizationResponse retVal = this.EndGetAuthorizationList(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAuthorizationListCompleted(object state) {
            if ((this.GetAuthorizationListCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAuthorizationListCompleted(this, new GetAuthorizationListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAuthorizationListAsync(ChannelAdvisorAccess.AdminService.APICredentials APICredentials, string localID) {
            this.GetAuthorizationListAsync(APICredentials, localID, null);
        }
        
        public void GetAuthorizationListAsync(ChannelAdvisorAccess.AdminService.APICredentials APICredentials, string localID, object userState) {
            if ((this.onBeginGetAuthorizationListDelegate == null)) {
                this.onBeginGetAuthorizationListDelegate = new BeginOperationDelegate(this.OnBeginGetAuthorizationList);
            }
            if ((this.onEndGetAuthorizationListDelegate == null)) {
                this.onEndGetAuthorizationListDelegate = new EndOperationDelegate(this.OnEndGetAuthorizationList);
            }
            if ((this.onGetAuthorizationListCompletedDelegate == null)) {
                this.onGetAuthorizationListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAuthorizationListCompleted);
            }
            base.InvokeAsync(this.onBeginGetAuthorizationListDelegate, new object[] {
                        APICredentials,
                        localID}, this.onEndGetAuthorizationListDelegate, this.onGetAuthorizationListCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChannelAdvisorAccess.AdminService.RequestAccessResponse ChannelAdvisorAccess.AdminService.AdminServiceSoap.RequestAccess(ChannelAdvisorAccess.AdminService.RequestAccessRequest request) {
            return base.Channel.RequestAccess(request);
        }
        
        public ChannelAdvisorAccess.AdminService.APIResultOfBoolean RequestAccess(ChannelAdvisorAccess.AdminService.APICredentials APICredentials, int localID) {
            ChannelAdvisorAccess.AdminService.RequestAccessRequest inValue = new ChannelAdvisorAccess.AdminService.RequestAccessRequest();
            inValue.APICredentials = APICredentials;
            inValue.localID = localID;
            ChannelAdvisorAccess.AdminService.RequestAccessResponse retVal = ((ChannelAdvisorAccess.AdminService.AdminServiceSoap)(this)).RequestAccess(inValue);
            return retVal.RequestAccessResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ChannelAdvisorAccess.AdminService.AdminServiceSoap.BeginRequestAccess(ChannelAdvisorAccess.AdminService.RequestAccessRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRequestAccess(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginRequestAccess(ChannelAdvisorAccess.AdminService.APICredentials APICredentials, int localID, System.AsyncCallback callback, object asyncState) {
            ChannelAdvisorAccess.AdminService.RequestAccessRequest inValue = new ChannelAdvisorAccess.AdminService.RequestAccessRequest();
            inValue.APICredentials = APICredentials;
            inValue.localID = localID;
            return ((ChannelAdvisorAccess.AdminService.AdminServiceSoap)(this)).BeginRequestAccess(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChannelAdvisorAccess.AdminService.RequestAccessResponse ChannelAdvisorAccess.AdminService.AdminServiceSoap.EndRequestAccess(System.IAsyncResult result) {
            return base.Channel.EndRequestAccess(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ChannelAdvisorAccess.AdminService.APIResultOfBoolean EndRequestAccess(System.IAsyncResult result) {
            ChannelAdvisorAccess.AdminService.RequestAccessResponse retVal = ((ChannelAdvisorAccess.AdminService.AdminServiceSoap)(this)).EndRequestAccess(result);
            return retVal.RequestAccessResult;
        }
        
        private System.IAsyncResult OnBeginRequestAccess(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ChannelAdvisorAccess.AdminService.APICredentials APICredentials = ((ChannelAdvisorAccess.AdminService.APICredentials)(inValues[0]));
            int localID = ((int)(inValues[1]));
            return this.BeginRequestAccess(APICredentials, localID, callback, asyncState);
        }
        
        private object[] OnEndRequestAccess(System.IAsyncResult result) {
            ChannelAdvisorAccess.AdminService.APIResultOfBoolean retVal = this.EndRequestAccess(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRequestAccessCompleted(object state) {
            if ((this.RequestAccessCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RequestAccessCompleted(this, new RequestAccessCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RequestAccessAsync(ChannelAdvisorAccess.AdminService.APICredentials APICredentials, int localID) {
            this.RequestAccessAsync(APICredentials, localID, null);
        }
        
        public void RequestAccessAsync(ChannelAdvisorAccess.AdminService.APICredentials APICredentials, int localID, object userState) {
            if ((this.onBeginRequestAccessDelegate == null)) {
                this.onBeginRequestAccessDelegate = new BeginOperationDelegate(this.OnBeginRequestAccess);
            }
            if ((this.onEndRequestAccessDelegate == null)) {
                this.onEndRequestAccessDelegate = new EndOperationDelegate(this.OnEndRequestAccess);
            }
            if ((this.onRequestAccessCompletedDelegate == null)) {
                this.onRequestAccessCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRequestAccessCompleted);
            }
            base.InvokeAsync(this.onBeginRequestAccessDelegate, new object[] {
                        APICredentials,
                        localID}, this.onEndRequestAccessDelegate, this.onRequestAccessCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChannelAdvisorAccess.AdminService.PingResponse ChannelAdvisorAccess.AdminService.AdminServiceSoap.Ping(ChannelAdvisorAccess.AdminService.PingRequest request) {
            return base.Channel.Ping(request);
        }
        
        public ChannelAdvisorAccess.AdminService.APIResultOfString Ping(ChannelAdvisorAccess.AdminService.APICredentials APICredentials) {
            ChannelAdvisorAccess.AdminService.PingRequest inValue = new ChannelAdvisorAccess.AdminService.PingRequest();
            inValue.APICredentials = APICredentials;
            ChannelAdvisorAccess.AdminService.PingResponse retVal = ((ChannelAdvisorAccess.AdminService.AdminServiceSoap)(this)).Ping(inValue);
            return retVal.PingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ChannelAdvisorAccess.AdminService.AdminServiceSoap.BeginPing(ChannelAdvisorAccess.AdminService.PingRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPing(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginPing(ChannelAdvisorAccess.AdminService.APICredentials APICredentials, System.AsyncCallback callback, object asyncState) {
            ChannelAdvisorAccess.AdminService.PingRequest inValue = new ChannelAdvisorAccess.AdminService.PingRequest();
            inValue.APICredentials = APICredentials;
            return ((ChannelAdvisorAccess.AdminService.AdminServiceSoap)(this)).BeginPing(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChannelAdvisorAccess.AdminService.PingResponse ChannelAdvisorAccess.AdminService.AdminServiceSoap.EndPing(System.IAsyncResult result) {
            return base.Channel.EndPing(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ChannelAdvisorAccess.AdminService.APIResultOfString EndPing(System.IAsyncResult result) {
            ChannelAdvisorAccess.AdminService.PingResponse retVal = ((ChannelAdvisorAccess.AdminService.AdminServiceSoap)(this)).EndPing(result);
            return retVal.PingResult;
        }
        
        private System.IAsyncResult OnBeginPing(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ChannelAdvisorAccess.AdminService.APICredentials APICredentials = ((ChannelAdvisorAccess.AdminService.APICredentials)(inValues[0]));
            return this.BeginPing(APICredentials, callback, asyncState);
        }
        
        private object[] OnEndPing(System.IAsyncResult result) {
            ChannelAdvisorAccess.AdminService.APIResultOfString retVal = this.EndPing(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPingCompleted(object state) {
            if ((this.PingCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PingCompleted(this, new PingCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PingAsync(ChannelAdvisorAccess.AdminService.APICredentials APICredentials) {
            this.PingAsync(APICredentials, null);
        }
        
        public void PingAsync(ChannelAdvisorAccess.AdminService.APICredentials APICredentials, object userState) {
            if ((this.onBeginPingDelegate == null)) {
                this.onBeginPingDelegate = new BeginOperationDelegate(this.OnBeginPing);
            }
            if ((this.onEndPingDelegate == null)) {
                this.onEndPingDelegate = new EndOperationDelegate(this.OnEndPing);
            }
            if ((this.onPingCompletedDelegate == null)) {
                this.onPingCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPingCompleted);
            }
            base.InvokeAsync(this.onBeginPingDelegate, new object[] {
                        APICredentials}, this.onEndPingDelegate, this.onPingCompletedDelegate, userState);
        }
    }
}
