//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannelAdvisorAccess.FulfillmentService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.channeladvisor.com/webservices/", ConfigurationName="FulfillmentService.FulfillmentServiceSoap")]
    public interface FulfillmentServiceSoap {
        
        // CODEGEN: Generating message contract since message GetOrderFulfillmentDetailListRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://api.channeladvisor.com/webservices/GetOrderFulfillmentDetailList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ChannelAdvisorAccess.FulfillmentService.GetOrderFulfillmentDetailListResponse GetOrderFulfillmentDetailList(ChannelAdvisorAccess.FulfillmentService.GetOrderFulfillmentDetailListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.channeladvisor.com/webservices/GetOrderFulfillmentDetailList", ReplyAction="*")]
        System.Threading.Tasks.Task<ChannelAdvisorAccess.FulfillmentService.GetOrderFulfillmentDetailListResponse> GetOrderFulfillmentDetailListAsync(ChannelAdvisorAccess.FulfillmentService.GetOrderFulfillmentDetailListRequest request);
        
        // CODEGEN: Generating message contract since message UpdateOrderFulfillmentsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://api.channeladvisor.com/webservices/UpdateOrderFulfillments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ChannelAdvisorAccess.FulfillmentService.UpdateOrderFulfillmentsResponse UpdateOrderFulfillments(ChannelAdvisorAccess.FulfillmentService.UpdateOrderFulfillmentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.channeladvisor.com/webservices/UpdateOrderFulfillments", ReplyAction="*")]
        System.Threading.Tasks.Task<ChannelAdvisorAccess.FulfillmentService.UpdateOrderFulfillmentsResponse> UpdateOrderFulfillmentsAsync(ChannelAdvisorAccess.FulfillmentService.UpdateOrderFulfillmentsRequest request);
        
        // CODEGEN: Generating message contract since message CreateOrderFulfillmentsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://api.channeladvisor.com/webservices/CreateOrderFulfillments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ChannelAdvisorAccess.FulfillmentService.CreateOrderFulfillmentsResponse CreateOrderFulfillments(ChannelAdvisorAccess.FulfillmentService.CreateOrderFulfillmentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.channeladvisor.com/webservices/CreateOrderFulfillments", ReplyAction="*")]
        System.Threading.Tasks.Task<ChannelAdvisorAccess.FulfillmentService.CreateOrderFulfillmentsResponse> CreateOrderFulfillmentsAsync(ChannelAdvisorAccess.FulfillmentService.CreateOrderFulfillmentsRequest request);
        
        // CODEGEN: Generating message contract since message MoveFulfillmentItemsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://api.channeladvisor.com/webservices/MoveFulfillmentItems", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ChannelAdvisorAccess.FulfillmentService.MoveFulfillmentItemsResponse MoveFulfillmentItems(ChannelAdvisorAccess.FulfillmentService.MoveFulfillmentItemsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.channeladvisor.com/webservices/MoveFulfillmentItems", ReplyAction="*")]
        System.Threading.Tasks.Task<ChannelAdvisorAccess.FulfillmentService.MoveFulfillmentItemsResponse> MoveFulfillmentItemsAsync(ChannelAdvisorAccess.FulfillmentService.MoveFulfillmentItemsRequest request);
        
        // CODEGEN: Generating message contract since message PingRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://api.channeladvisor.com/webservices/Ping", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ChannelAdvisorAccess.FulfillmentService.PingResponse Ping(ChannelAdvisorAccess.FulfillmentService.PingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.channeladvisor.com/webservices/Ping", ReplyAction="*")]
        System.Threading.Tasks.Task<ChannelAdvisorAccess.FulfillmentService.PingResponse> PingAsync(ChannelAdvisorAccess.FulfillmentService.PingRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class APICredentials : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string developerKeyField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DeveloperKey {
            get {
                return this.developerKeyField;
            }
            set {
                this.developerKeyField = value;
                this.RaisePropertyChanged("DeveloperKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class APIResultOfString : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultStatus statusField;
        
        private int messageCodeField;
        
        private string messageField;
        
        private string dataField;
        
        private string resultDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResultStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int MessageCode {
            get {
                return this.messageCodeField;
            }
            set {
                this.messageCodeField = value;
                this.RaisePropertyChanged("MessageCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ResultData {
            get {
                return this.resultDataField;
            }
            set {
                this.resultDataField = value;
                this.RaisePropertyChanged("ResultData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public enum ResultStatus {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Failure,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class FulfillmentItemMoveResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int fulfillmentItemIDField;
        
        private bool successField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int FulfillmentItemID {
            get {
                return this.fulfillmentItemIDField;
            }
            set {
                this.fulfillmentItemIDField = value;
                this.RaisePropertyChanged("FulfillmentItemID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class APIResultOfArrayOfFulfillmentItemMoveResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultStatus statusField;
        
        private int messageCodeField;
        
        private string messageField;
        
        private string dataField;
        
        private FulfillmentItemMoveResponse[] resultDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResultStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int MessageCode {
            get {
                return this.messageCodeField;
            }
            set {
                this.messageCodeField = value;
                this.RaisePropertyChanged("MessageCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public FulfillmentItemMoveResponse[] ResultData {
            get {
                return this.resultDataField;
            }
            set {
                this.resultDataField = value;
                this.RaisePropertyChanged("ResultData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class FulfillmentItemSubmit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int fulfillmentItemIDField;
        
        private int quantityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int FulfillmentItemID {
            get {
                return this.fulfillmentItemIDField;
            }
            set {
                this.fulfillmentItemIDField = value;
                this.RaisePropertyChanged("FulfillmentItemID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class FulfillmentCreateSubmit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fulfillmentTypeField;
        
        private string fulfillmentStatusField;
        
        private string carrierCodeField;
        
        private string classCodeField;
        
        private string trackingNumberField;
        
        private string distributionCenterCodeField;
        
        private System.Nullable<decimal> costField;
        
        private System.Nullable<decimal> taxCostField;
        
        private System.Nullable<decimal> insuranceCostField;
        
        private System.Nullable<System.DateTime> shippedDateGMTField;
        
        private string sellerFulfillmentIDField;
        
        private FulfillmentItemSubmit[] itemListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FulfillmentType {
            get {
                return this.fulfillmentTypeField;
            }
            set {
                this.fulfillmentTypeField = value;
                this.RaisePropertyChanged("FulfillmentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FulfillmentStatus {
            get {
                return this.fulfillmentStatusField;
            }
            set {
                this.fulfillmentStatusField = value;
                this.RaisePropertyChanged("FulfillmentStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CarrierCode {
            get {
                return this.carrierCodeField;
            }
            set {
                this.carrierCodeField = value;
                this.RaisePropertyChanged("CarrierCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ClassCode {
            get {
                return this.classCodeField;
            }
            set {
                this.classCodeField = value;
                this.RaisePropertyChanged("ClassCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TrackingNumber {
            get {
                return this.trackingNumberField;
            }
            set {
                this.trackingNumberField = value;
                this.RaisePropertyChanged("TrackingNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DistributionCenterCode {
            get {
                return this.distributionCenterCodeField;
            }
            set {
                this.distributionCenterCodeField = value;
                this.RaisePropertyChanged("DistributionCenterCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<decimal> Cost {
            get {
                return this.costField;
            }
            set {
                this.costField = value;
                this.RaisePropertyChanged("Cost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<decimal> TaxCost {
            get {
                return this.taxCostField;
            }
            set {
                this.taxCostField = value;
                this.RaisePropertyChanged("TaxCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<decimal> InsuranceCost {
            get {
                return this.insuranceCostField;
            }
            set {
                this.insuranceCostField = value;
                this.RaisePropertyChanged("InsuranceCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<System.DateTime> ShippedDateGMT {
            get {
                return this.shippedDateGMTField;
            }
            set {
                this.shippedDateGMTField = value;
                this.RaisePropertyChanged("ShippedDateGMT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string SellerFulfillmentID {
            get {
                return this.sellerFulfillmentIDField;
            }
            set {
                this.sellerFulfillmentIDField = value;
                this.RaisePropertyChanged("SellerFulfillmentID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=11)]
        public FulfillmentItemSubmit[] ItemList {
            get {
                return this.itemListField;
            }
            set {
                this.itemListField = value;
                this.RaisePropertyChanged("ItemList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class FulfillmentOperationResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int fulfillmentIDField;
        
        private bool successField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int FulfillmentID {
            get {
                return this.fulfillmentIDField;
            }
            set {
                this.fulfillmentIDField = value;
                this.RaisePropertyChanged("FulfillmentID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class APIResultOfArrayOfFulfillmentOperationResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultStatus statusField;
        
        private int messageCodeField;
        
        private string messageField;
        
        private string dataField;
        
        private FulfillmentOperationResponse[] resultDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResultStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int MessageCode {
            get {
                return this.messageCodeField;
            }
            set {
                this.messageCodeField = value;
                this.RaisePropertyChanged("MessageCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public FulfillmentOperationResponse[] ResultData {
            get {
                return this.resultDataField;
            }
            set {
                this.resultDataField = value;
                this.RaisePropertyChanged("ResultData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class FulfillmentUpdateSubmit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int fulfillmentIDField;
        
        private string fulfillmentTypeField;
        
        private string fulfillmentStatusField;
        
        private string carrierCodeField;
        
        private string classCodeField;
        
        private string trackingNumberField;
        
        private System.Nullable<decimal> costField;
        
        private System.Nullable<decimal> taxCostField;
        
        private System.Nullable<decimal> insuranceCostField;
        
        private System.Nullable<System.DateTime> shippedDateGMTField;
        
        private string sellerFulfillmentIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int FulfillmentID {
            get {
                return this.fulfillmentIDField;
            }
            set {
                this.fulfillmentIDField = value;
                this.RaisePropertyChanged("FulfillmentID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FulfillmentType {
            get {
                return this.fulfillmentTypeField;
            }
            set {
                this.fulfillmentTypeField = value;
                this.RaisePropertyChanged("FulfillmentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FulfillmentStatus {
            get {
                return this.fulfillmentStatusField;
            }
            set {
                this.fulfillmentStatusField = value;
                this.RaisePropertyChanged("FulfillmentStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CarrierCode {
            get {
                return this.carrierCodeField;
            }
            set {
                this.carrierCodeField = value;
                this.RaisePropertyChanged("CarrierCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ClassCode {
            get {
                return this.classCodeField;
            }
            set {
                this.classCodeField = value;
                this.RaisePropertyChanged("ClassCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TrackingNumber {
            get {
                return this.trackingNumberField;
            }
            set {
                this.trackingNumberField = value;
                this.RaisePropertyChanged("TrackingNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<decimal> Cost {
            get {
                return this.costField;
            }
            set {
                this.costField = value;
                this.RaisePropertyChanged("Cost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<decimal> TaxCost {
            get {
                return this.taxCostField;
            }
            set {
                this.taxCostField = value;
                this.RaisePropertyChanged("TaxCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<decimal> InsuranceCost {
            get {
                return this.insuranceCostField;
            }
            set {
                this.insuranceCostField = value;
                this.RaisePropertyChanged("InsuranceCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<System.DateTime> ShippedDateGMT {
            get {
                return this.shippedDateGMTField;
            }
            set {
                this.shippedDateGMTField = value;
                this.RaisePropertyChanged("ShippedDateGMT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string SellerFulfillmentID {
            get {
                return this.sellerFulfillmentIDField;
            }
            set {
                this.sellerFulfillmentIDField = value;
                this.RaisePropertyChanged("SellerFulfillmentID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class FulfillmentItemDetailResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int fulfillmentItemIDField;
        
        private string sKUField;
        
        private int quantityField;
        
        private int lineItemIDField;
        
        private string siteAuctionIDField;
        
        private string saleSourceIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int FulfillmentItemID {
            get {
                return this.fulfillmentItemIDField;
            }
            set {
                this.fulfillmentItemIDField = value;
                this.RaisePropertyChanged("FulfillmentItemID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SKU {
            get {
                return this.sKUField;
            }
            set {
                this.sKUField = value;
                this.RaisePropertyChanged("SKU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int LineItemID {
            get {
                return this.lineItemIDField;
            }
            set {
                this.lineItemIDField = value;
                this.RaisePropertyChanged("LineItemID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SiteAuctionID {
            get {
                return this.siteAuctionIDField;
            }
            set {
                this.siteAuctionIDField = value;
                this.RaisePropertyChanged("SiteAuctionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SaleSourceID {
            get {
                return this.saleSourceIDField;
            }
            set {
                this.saleSourceIDField = value;
                this.RaisePropertyChanged("SaleSourceID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class FulfillmentDetailResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int fulfillmentIDField;
        
        private System.DateTime createdDateGMTField;
        
        private System.DateTime updatedDateGMTField;
        
        private string fulfillmentTypeField;
        
        private string fulfillmentStatusField;
        
        private string carrierCodeField;
        
        private string classCodeField;
        
        private string trackingNumberField;
        
        private string distributionCenterCodeField;
        
        private System.Nullable<decimal> costField;
        
        private System.Nullable<decimal> taxCostField;
        
        private System.Nullable<decimal> insuranceCostField;
        
        private System.Nullable<System.DateTime> shippedDateGMTField;
        
        private string sellerFulfillmentIDField;
        
        private FulfillmentItemDetailResponse[] itemListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int FulfillmentID {
            get {
                return this.fulfillmentIDField;
            }
            set {
                this.fulfillmentIDField = value;
                this.RaisePropertyChanged("FulfillmentID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime CreatedDateGMT {
            get {
                return this.createdDateGMTField;
            }
            set {
                this.createdDateGMTField = value;
                this.RaisePropertyChanged("CreatedDateGMT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime UpdatedDateGMT {
            get {
                return this.updatedDateGMTField;
            }
            set {
                this.updatedDateGMTField = value;
                this.RaisePropertyChanged("UpdatedDateGMT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FulfillmentType {
            get {
                return this.fulfillmentTypeField;
            }
            set {
                this.fulfillmentTypeField = value;
                this.RaisePropertyChanged("FulfillmentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string FulfillmentStatus {
            get {
                return this.fulfillmentStatusField;
            }
            set {
                this.fulfillmentStatusField = value;
                this.RaisePropertyChanged("FulfillmentStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CarrierCode {
            get {
                return this.carrierCodeField;
            }
            set {
                this.carrierCodeField = value;
                this.RaisePropertyChanged("CarrierCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ClassCode {
            get {
                return this.classCodeField;
            }
            set {
                this.classCodeField = value;
                this.RaisePropertyChanged("ClassCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string TrackingNumber {
            get {
                return this.trackingNumberField;
            }
            set {
                this.trackingNumberField = value;
                this.RaisePropertyChanged("TrackingNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string DistributionCenterCode {
            get {
                return this.distributionCenterCodeField;
            }
            set {
                this.distributionCenterCodeField = value;
                this.RaisePropertyChanged("DistributionCenterCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<decimal> Cost {
            get {
                return this.costField;
            }
            set {
                this.costField = value;
                this.RaisePropertyChanged("Cost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<decimal> TaxCost {
            get {
                return this.taxCostField;
            }
            set {
                this.taxCostField = value;
                this.RaisePropertyChanged("TaxCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<decimal> InsuranceCost {
            get {
                return this.insuranceCostField;
            }
            set {
                this.insuranceCostField = value;
                this.RaisePropertyChanged("InsuranceCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<System.DateTime> ShippedDateGMT {
            get {
                return this.shippedDateGMTField;
            }
            set {
                this.shippedDateGMTField = value;
                this.RaisePropertyChanged("ShippedDateGMT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string SellerFulfillmentID {
            get {
                return this.sellerFulfillmentIDField;
            }
            set {
                this.sellerFulfillmentIDField = value;
                this.RaisePropertyChanged("SellerFulfillmentID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=14)]
        public FulfillmentItemDetailResponse[] ItemList {
            get {
                return this.itemListField;
            }
            set {
                this.itemListField = value;
                this.RaisePropertyChanged("ItemList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class OrderFulfillmentResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int orderIDField;
        
        private string clientOrderIdentifierField;
        
        private FulfillmentDetailResponse[] fulfillmentListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int OrderID {
            get {
                return this.orderIDField;
            }
            set {
                this.orderIDField = value;
                this.RaisePropertyChanged("OrderID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ClientOrderIdentifier {
            get {
                return this.clientOrderIdentifierField;
            }
            set {
                this.clientOrderIdentifierField = value;
                this.RaisePropertyChanged("ClientOrderIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public FulfillmentDetailResponse[] FulfillmentList {
            get {
                return this.fulfillmentListField;
            }
            set {
                this.fulfillmentListField = value;
                this.RaisePropertyChanged("FulfillmentList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class APIResultOfArrayOfOrderFulfillmentResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultStatus statusField;
        
        private int messageCodeField;
        
        private string messageField;
        
        private string dataField;
        
        private OrderFulfillmentResponse[] resultDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResultStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int MessageCode {
            get {
                return this.messageCodeField;
            }
            set {
                this.messageCodeField = value;
                this.RaisePropertyChanged("MessageCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public OrderFulfillmentResponse[] ResultData {
            get {
                return this.resultDataField;
            }
            set {
                this.resultDataField = value;
                this.RaisePropertyChanged("ResultData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOrderFulfillmentDetailList", WrapperNamespace="http://api.channeladvisor.com/webservices/", IsWrapped=true)]
    public partial class GetOrderFulfillmentDetailListRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
        public ChannelAdvisorAccess.FulfillmentService.APICredentials APICredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string accountID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=1)]
        public int[] orderIDList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=2)]
        public string[] clientOrderIdentifierList;
        
        public GetOrderFulfillmentDetailListRequest() {
        }
        
        public GetOrderFulfillmentDetailListRequest(ChannelAdvisorAccess.FulfillmentService.APICredentials APICredentials, string accountID, int[] orderIDList, string[] clientOrderIdentifierList) {
            this.APICredentials = APICredentials;
            this.accountID = accountID;
            this.orderIDList = orderIDList;
            this.clientOrderIdentifierList = clientOrderIdentifierList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOrderFulfillmentDetailListResponse", WrapperNamespace="http://api.channeladvisor.com/webservices/", IsWrapped=true)]
    public partial class GetOrderFulfillmentDetailListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=0)]
        public ChannelAdvisorAccess.FulfillmentService.APIResultOfArrayOfOrderFulfillmentResponse GetOrderFulfillmentDetailListResult;
        
        public GetOrderFulfillmentDetailListResponse() {
        }
        
        public GetOrderFulfillmentDetailListResponse(ChannelAdvisorAccess.FulfillmentService.APIResultOfArrayOfOrderFulfillmentResponse GetOrderFulfillmentDetailListResult) {
            this.GetOrderFulfillmentDetailListResult = GetOrderFulfillmentDetailListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateOrderFulfillments", WrapperNamespace="http://api.channeladvisor.com/webservices/", IsWrapped=true)]
    public partial class UpdateOrderFulfillmentsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
        public ChannelAdvisorAccess.FulfillmentService.APICredentials APICredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string accountID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> orderID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=2)]
        public string clientOrderIdentifier;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=3)]
        public ChannelAdvisorAccess.FulfillmentService.FulfillmentUpdateSubmit[] fulfillmentUpdateList;
        
        public UpdateOrderFulfillmentsRequest() {
        }
        
        public UpdateOrderFulfillmentsRequest(ChannelAdvisorAccess.FulfillmentService.APICredentials APICredentials, string accountID, System.Nullable<int> orderID, string clientOrderIdentifier, ChannelAdvisorAccess.FulfillmentService.FulfillmentUpdateSubmit[] fulfillmentUpdateList) {
            this.APICredentials = APICredentials;
            this.accountID = accountID;
            this.orderID = orderID;
            this.clientOrderIdentifier = clientOrderIdentifier;
            this.fulfillmentUpdateList = fulfillmentUpdateList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateOrderFulfillmentsResponse", WrapperNamespace="http://api.channeladvisor.com/webservices/", IsWrapped=true)]
    public partial class UpdateOrderFulfillmentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=0)]
        public ChannelAdvisorAccess.FulfillmentService.APIResultOfArrayOfFulfillmentOperationResponse UpdateOrderFulfillmentsResult;
        
        public UpdateOrderFulfillmentsResponse() {
        }
        
        public UpdateOrderFulfillmentsResponse(ChannelAdvisorAccess.FulfillmentService.APIResultOfArrayOfFulfillmentOperationResponse UpdateOrderFulfillmentsResult) {
            this.UpdateOrderFulfillmentsResult = UpdateOrderFulfillmentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateOrderFulfillments", WrapperNamespace="http://api.channeladvisor.com/webservices/", IsWrapped=true)]
    public partial class CreateOrderFulfillmentsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
        public ChannelAdvisorAccess.FulfillmentService.APICredentials APICredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string accountID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> orderID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=2)]
        public string clientOrderIdentifier;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=3)]
        public ChannelAdvisorAccess.FulfillmentService.FulfillmentCreateSubmit[] fulfillmentList;
        
        public CreateOrderFulfillmentsRequest() {
        }
        
        public CreateOrderFulfillmentsRequest(ChannelAdvisorAccess.FulfillmentService.APICredentials APICredentials, string accountID, System.Nullable<int> orderID, string clientOrderIdentifier, ChannelAdvisorAccess.FulfillmentService.FulfillmentCreateSubmit[] fulfillmentList) {
            this.APICredentials = APICredentials;
            this.accountID = accountID;
            this.orderID = orderID;
            this.clientOrderIdentifier = clientOrderIdentifier;
            this.fulfillmentList = fulfillmentList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateOrderFulfillmentsResponse", WrapperNamespace="http://api.channeladvisor.com/webservices/", IsWrapped=true)]
    public partial class CreateOrderFulfillmentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=0)]
        public ChannelAdvisorAccess.FulfillmentService.APIResultOfArrayOfFulfillmentOperationResponse CreateOrderFulfillmentsResult;
        
        public CreateOrderFulfillmentsResponse() {
        }
        
        public CreateOrderFulfillmentsResponse(ChannelAdvisorAccess.FulfillmentService.APIResultOfArrayOfFulfillmentOperationResponse CreateOrderFulfillmentsResult) {
            this.CreateOrderFulfillmentsResult = CreateOrderFulfillmentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MoveFulfillmentItems", WrapperNamespace="http://api.channeladvisor.com/webservices/", IsWrapped=true)]
    public partial class MoveFulfillmentItemsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
        public ChannelAdvisorAccess.FulfillmentService.APICredentials APICredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string accountID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> orderID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=2)]
        public string clientOrderIdentifier;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=3)]
        public int destinationFulfillmentID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=4)]
        public ChannelAdvisorAccess.FulfillmentService.FulfillmentItemSubmit[] sourceFulfillmentItemList;
        
        public MoveFulfillmentItemsRequest() {
        }
        
        public MoveFulfillmentItemsRequest(ChannelAdvisorAccess.FulfillmentService.APICredentials APICredentials, string accountID, System.Nullable<int> orderID, string clientOrderIdentifier, int destinationFulfillmentID, ChannelAdvisorAccess.FulfillmentService.FulfillmentItemSubmit[] sourceFulfillmentItemList) {
            this.APICredentials = APICredentials;
            this.accountID = accountID;
            this.orderID = orderID;
            this.clientOrderIdentifier = clientOrderIdentifier;
            this.destinationFulfillmentID = destinationFulfillmentID;
            this.sourceFulfillmentItemList = sourceFulfillmentItemList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MoveFulfillmentItemsResponse", WrapperNamespace="http://api.channeladvisor.com/webservices/", IsWrapped=true)]
    public partial class MoveFulfillmentItemsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=0)]
        public ChannelAdvisorAccess.FulfillmentService.APIResultOfArrayOfFulfillmentItemMoveResponse MoveFulfillmentItemsResult;
        
        public MoveFulfillmentItemsResponse() {
        }
        
        public MoveFulfillmentItemsResponse(ChannelAdvisorAccess.FulfillmentService.APIResultOfArrayOfFulfillmentItemMoveResponse MoveFulfillmentItemsResult) {
            this.MoveFulfillmentItemsResult = MoveFulfillmentItemsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Ping", WrapperNamespace="http://api.channeladvisor.com/webservices/", IsWrapped=true)]
    public partial class PingRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
        public ChannelAdvisorAccess.FulfillmentService.APICredentials APICredentials;
        
        public PingRequest() {
        }
        
        public PingRequest(ChannelAdvisorAccess.FulfillmentService.APICredentials APICredentials) {
            this.APICredentials = APICredentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PingResponse", WrapperNamespace="http://api.channeladvisor.com/webservices/", IsWrapped=true)]
    public partial class PingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.channeladvisor.com/webservices/", Order=0)]
        public ChannelAdvisorAccess.FulfillmentService.APIResultOfString PingResult;
        
        public PingResponse() {
        }
        
        public PingResponse(ChannelAdvisorAccess.FulfillmentService.APIResultOfString PingResult) {
            this.PingResult = PingResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FulfillmentServiceSoapChannel : ChannelAdvisorAccess.FulfillmentService.FulfillmentServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FulfillmentServiceSoapClient : System.ServiceModel.ClientBase<ChannelAdvisorAccess.FulfillmentService.FulfillmentServiceSoap>, ChannelAdvisorAccess.FulfillmentService.FulfillmentServiceSoap {
        
        public FulfillmentServiceSoapClient() {
        }
        
        public FulfillmentServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FulfillmentServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FulfillmentServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FulfillmentServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChannelAdvisorAccess.FulfillmentService.GetOrderFulfillmentDetailListResponse ChannelAdvisorAccess.FulfillmentService.FulfillmentServiceSoap.GetOrderFulfillmentDetailList(ChannelAdvisorAccess.FulfillmentService.GetOrderFulfillmentDetailListRequest request) {
            return base.Channel.GetOrderFulfillmentDetailList(request);
        }
        
        public ChannelAdvisorAccess.FulfillmentService.APIResultOfArrayOfOrderFulfillmentResponse GetOrderFulfillmentDetailList(ChannelAdvisorAccess.FulfillmentService.APICredentials APICredentials, string accountID, int[] orderIDList, string[] clientOrderIdentifierList) {
            ChannelAdvisorAccess.FulfillmentService.GetOrderFulfillmentDetailListRequest inValue = new ChannelAdvisorAccess.FulfillmentService.GetOrderFulfillmentDetailListRequest();
            inValue.APICredentials = APICredentials;
            inValue.accountID = accountID;
            inValue.orderIDList = orderIDList;
            inValue.clientOrderIdentifierList = clientOrderIdentifierList;
            ChannelAdvisorAccess.FulfillmentService.GetOrderFulfillmentDetailListResponse retVal = ((ChannelAdvisorAccess.FulfillmentService.FulfillmentServiceSoap)(this)).GetOrderFulfillmentDetailList(inValue);
            return retVal.GetOrderFulfillmentDetailListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ChannelAdvisorAccess.FulfillmentService.GetOrderFulfillmentDetailListResponse> ChannelAdvisorAccess.FulfillmentService.FulfillmentServiceSoap.GetOrderFulfillmentDetailListAsync(ChannelAdvisorAccess.FulfillmentService.GetOrderFulfillmentDetailListRequest request) {
            return base.Channel.GetOrderFulfillmentDetailListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ChannelAdvisorAccess.FulfillmentService.GetOrderFulfillmentDetailListResponse> GetOrderFulfillmentDetailListAsync(ChannelAdvisorAccess.FulfillmentService.APICredentials APICredentials, string accountID, int[] orderIDList, string[] clientOrderIdentifierList) {
            ChannelAdvisorAccess.FulfillmentService.GetOrderFulfillmentDetailListRequest inValue = new ChannelAdvisorAccess.FulfillmentService.GetOrderFulfillmentDetailListRequest();
            inValue.APICredentials = APICredentials;
            inValue.accountID = accountID;
            inValue.orderIDList = orderIDList;
            inValue.clientOrderIdentifierList = clientOrderIdentifierList;
            return ((ChannelAdvisorAccess.FulfillmentService.FulfillmentServiceSoap)(this)).GetOrderFulfillmentDetailListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChannelAdvisorAccess.FulfillmentService.UpdateOrderFulfillmentsResponse ChannelAdvisorAccess.FulfillmentService.FulfillmentServiceSoap.UpdateOrderFulfillments(ChannelAdvisorAccess.FulfillmentService.UpdateOrderFulfillmentsRequest request) {
            return base.Channel.UpdateOrderFulfillments(request);
        }
        
        public ChannelAdvisorAccess.FulfillmentService.APIResultOfArrayOfFulfillmentOperationResponse UpdateOrderFulfillments(ChannelAdvisorAccess.FulfillmentService.APICredentials APICredentials, string accountID, System.Nullable<int> orderID, string clientOrderIdentifier, ChannelAdvisorAccess.FulfillmentService.FulfillmentUpdateSubmit[] fulfillmentUpdateList) {
            ChannelAdvisorAccess.FulfillmentService.UpdateOrderFulfillmentsRequest inValue = new ChannelAdvisorAccess.FulfillmentService.UpdateOrderFulfillmentsRequest();
            inValue.APICredentials = APICredentials;
            inValue.accountID = accountID;
            inValue.orderID = orderID;
            inValue.clientOrderIdentifier = clientOrderIdentifier;
            inValue.fulfillmentUpdateList = fulfillmentUpdateList;
            ChannelAdvisorAccess.FulfillmentService.UpdateOrderFulfillmentsResponse retVal = ((ChannelAdvisorAccess.FulfillmentService.FulfillmentServiceSoap)(this)).UpdateOrderFulfillments(inValue);
            return retVal.UpdateOrderFulfillmentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ChannelAdvisorAccess.FulfillmentService.UpdateOrderFulfillmentsResponse> ChannelAdvisorAccess.FulfillmentService.FulfillmentServiceSoap.UpdateOrderFulfillmentsAsync(ChannelAdvisorAccess.FulfillmentService.UpdateOrderFulfillmentsRequest request) {
            return base.Channel.UpdateOrderFulfillmentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ChannelAdvisorAccess.FulfillmentService.UpdateOrderFulfillmentsResponse> UpdateOrderFulfillmentsAsync(ChannelAdvisorAccess.FulfillmentService.APICredentials APICredentials, string accountID, System.Nullable<int> orderID, string clientOrderIdentifier, ChannelAdvisorAccess.FulfillmentService.FulfillmentUpdateSubmit[] fulfillmentUpdateList) {
            ChannelAdvisorAccess.FulfillmentService.UpdateOrderFulfillmentsRequest inValue = new ChannelAdvisorAccess.FulfillmentService.UpdateOrderFulfillmentsRequest();
            inValue.APICredentials = APICredentials;
            inValue.accountID = accountID;
            inValue.orderID = orderID;
            inValue.clientOrderIdentifier = clientOrderIdentifier;
            inValue.fulfillmentUpdateList = fulfillmentUpdateList;
            return ((ChannelAdvisorAccess.FulfillmentService.FulfillmentServiceSoap)(this)).UpdateOrderFulfillmentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChannelAdvisorAccess.FulfillmentService.CreateOrderFulfillmentsResponse ChannelAdvisorAccess.FulfillmentService.FulfillmentServiceSoap.CreateOrderFulfillments(ChannelAdvisorAccess.FulfillmentService.CreateOrderFulfillmentsRequest request) {
            return base.Channel.CreateOrderFulfillments(request);
        }
        
        public ChannelAdvisorAccess.FulfillmentService.APIResultOfArrayOfFulfillmentOperationResponse CreateOrderFulfillments(ChannelAdvisorAccess.FulfillmentService.APICredentials APICredentials, string accountID, System.Nullable<int> orderID, string clientOrderIdentifier, ChannelAdvisorAccess.FulfillmentService.FulfillmentCreateSubmit[] fulfillmentList) {
            ChannelAdvisorAccess.FulfillmentService.CreateOrderFulfillmentsRequest inValue = new ChannelAdvisorAccess.FulfillmentService.CreateOrderFulfillmentsRequest();
            inValue.APICredentials = APICredentials;
            inValue.accountID = accountID;
            inValue.orderID = orderID;
            inValue.clientOrderIdentifier = clientOrderIdentifier;
            inValue.fulfillmentList = fulfillmentList;
            ChannelAdvisorAccess.FulfillmentService.CreateOrderFulfillmentsResponse retVal = ((ChannelAdvisorAccess.FulfillmentService.FulfillmentServiceSoap)(this)).CreateOrderFulfillments(inValue);
            return retVal.CreateOrderFulfillmentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ChannelAdvisorAccess.FulfillmentService.CreateOrderFulfillmentsResponse> ChannelAdvisorAccess.FulfillmentService.FulfillmentServiceSoap.CreateOrderFulfillmentsAsync(ChannelAdvisorAccess.FulfillmentService.CreateOrderFulfillmentsRequest request) {
            return base.Channel.CreateOrderFulfillmentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ChannelAdvisorAccess.FulfillmentService.CreateOrderFulfillmentsResponse> CreateOrderFulfillmentsAsync(ChannelAdvisorAccess.FulfillmentService.APICredentials APICredentials, string accountID, System.Nullable<int> orderID, string clientOrderIdentifier, ChannelAdvisorAccess.FulfillmentService.FulfillmentCreateSubmit[] fulfillmentList) {
            ChannelAdvisorAccess.FulfillmentService.CreateOrderFulfillmentsRequest inValue = new ChannelAdvisorAccess.FulfillmentService.CreateOrderFulfillmentsRequest();
            inValue.APICredentials = APICredentials;
            inValue.accountID = accountID;
            inValue.orderID = orderID;
            inValue.clientOrderIdentifier = clientOrderIdentifier;
            inValue.fulfillmentList = fulfillmentList;
            return ((ChannelAdvisorAccess.FulfillmentService.FulfillmentServiceSoap)(this)).CreateOrderFulfillmentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChannelAdvisorAccess.FulfillmentService.MoveFulfillmentItemsResponse ChannelAdvisorAccess.FulfillmentService.FulfillmentServiceSoap.MoveFulfillmentItems(ChannelAdvisorAccess.FulfillmentService.MoveFulfillmentItemsRequest request) {
            return base.Channel.MoveFulfillmentItems(request);
        }
        
        public ChannelAdvisorAccess.FulfillmentService.APIResultOfArrayOfFulfillmentItemMoveResponse MoveFulfillmentItems(ChannelAdvisorAccess.FulfillmentService.APICredentials APICredentials, string accountID, System.Nullable<int> orderID, string clientOrderIdentifier, int destinationFulfillmentID, ChannelAdvisorAccess.FulfillmentService.FulfillmentItemSubmit[] sourceFulfillmentItemList) {
            ChannelAdvisorAccess.FulfillmentService.MoveFulfillmentItemsRequest inValue = new ChannelAdvisorAccess.FulfillmentService.MoveFulfillmentItemsRequest();
            inValue.APICredentials = APICredentials;
            inValue.accountID = accountID;
            inValue.orderID = orderID;
            inValue.clientOrderIdentifier = clientOrderIdentifier;
            inValue.destinationFulfillmentID = destinationFulfillmentID;
            inValue.sourceFulfillmentItemList = sourceFulfillmentItemList;
            ChannelAdvisorAccess.FulfillmentService.MoveFulfillmentItemsResponse retVal = ((ChannelAdvisorAccess.FulfillmentService.FulfillmentServiceSoap)(this)).MoveFulfillmentItems(inValue);
            return retVal.MoveFulfillmentItemsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ChannelAdvisorAccess.FulfillmentService.MoveFulfillmentItemsResponse> ChannelAdvisorAccess.FulfillmentService.FulfillmentServiceSoap.MoveFulfillmentItemsAsync(ChannelAdvisorAccess.FulfillmentService.MoveFulfillmentItemsRequest request) {
            return base.Channel.MoveFulfillmentItemsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ChannelAdvisorAccess.FulfillmentService.MoveFulfillmentItemsResponse> MoveFulfillmentItemsAsync(ChannelAdvisorAccess.FulfillmentService.APICredentials APICredentials, string accountID, System.Nullable<int> orderID, string clientOrderIdentifier, int destinationFulfillmentID, ChannelAdvisorAccess.FulfillmentService.FulfillmentItemSubmit[] sourceFulfillmentItemList) {
            ChannelAdvisorAccess.FulfillmentService.MoveFulfillmentItemsRequest inValue = new ChannelAdvisorAccess.FulfillmentService.MoveFulfillmentItemsRequest();
            inValue.APICredentials = APICredentials;
            inValue.accountID = accountID;
            inValue.orderID = orderID;
            inValue.clientOrderIdentifier = clientOrderIdentifier;
            inValue.destinationFulfillmentID = destinationFulfillmentID;
            inValue.sourceFulfillmentItemList = sourceFulfillmentItemList;
            return ((ChannelAdvisorAccess.FulfillmentService.FulfillmentServiceSoap)(this)).MoveFulfillmentItemsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChannelAdvisorAccess.FulfillmentService.PingResponse ChannelAdvisorAccess.FulfillmentService.FulfillmentServiceSoap.Ping(ChannelAdvisorAccess.FulfillmentService.PingRequest request) {
            return base.Channel.Ping(request);
        }
        
        public ChannelAdvisorAccess.FulfillmentService.APIResultOfString Ping(ChannelAdvisorAccess.FulfillmentService.APICredentials APICredentials) {
            ChannelAdvisorAccess.FulfillmentService.PingRequest inValue = new ChannelAdvisorAccess.FulfillmentService.PingRequest();
            inValue.APICredentials = APICredentials;
            ChannelAdvisorAccess.FulfillmentService.PingResponse retVal = ((ChannelAdvisorAccess.FulfillmentService.FulfillmentServiceSoap)(this)).Ping(inValue);
            return retVal.PingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ChannelAdvisorAccess.FulfillmentService.PingResponse> ChannelAdvisorAccess.FulfillmentService.FulfillmentServiceSoap.PingAsync(ChannelAdvisorAccess.FulfillmentService.PingRequest request) {
            return base.Channel.PingAsync(request);
        }
        
        public System.Threading.Tasks.Task<ChannelAdvisorAccess.FulfillmentService.PingResponse> PingAsync(ChannelAdvisorAccess.FulfillmentService.APICredentials APICredentials) {
            ChannelAdvisorAccess.FulfillmentService.PingRequest inValue = new ChannelAdvisorAccess.FulfillmentService.PingRequest();
            inValue.APICredentials = APICredentials;
            return ((ChannelAdvisorAccess.FulfillmentService.FulfillmentServiceSoap)(this)).PingAsync(inValue);
        }
    }
}
